// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compiler/ir/serialization.common/src/KotlinIr.proto

package org.jetbrains.kotlin.backend.common.serialization.proto;

import org.jetbrains.kotlin.protobuf.AbstractParser;
import org.jetbrains.kotlin.protobuf.ByteString;
import org.jetbrains.kotlin.protobuf.CodedInputStream;
import org.jetbrains.kotlin.protobuf.CodedOutputStream;
import org.jetbrains.kotlin.protobuf.ExtensionRegistryLite;
import org.jetbrains.kotlin.protobuf.GeneratedMessageLite;
import org.jetbrains.kotlin.protobuf.InvalidProtocolBufferException;
import org.jetbrains.kotlin.protobuf.Parser;

import java.io.IOException;
import java.io.InputStream;
import java.io.ObjectStreamException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/**
 * Protobuf type {@code org.jetbrains.kotlin.backend.common.serialization.proto.ExpectActualTable}
 */
public final class ExpectActualTable extends
        GeneratedMessageLite implements
        // @@protoc_insertion_point(message_implements:org.jetbrains.kotlin.backend.common.serialization.proto.ExpectActualTable)
        ExpectActualTableOrBuilder {
    public static final int EXPECTTOACTUALS_FIELD_NUMBER = 1;
    private static final ExpectActualTable defaultInstance;
    private static final long serialVersionUID = 0L;
    public static Parser<ExpectActualTable> PARSER =
            new AbstractParser<ExpectActualTable>() {
                @Override
                public ExpectActualTable parsePartialFrom(
                        CodedInputStream input,
                        ExtensionRegistryLite extensionRegistry)
                        throws InvalidProtocolBufferException {
                    return new ExpectActualTable(input, extensionRegistry);
                }
            };

    static {
        defaultInstance = new ExpectActualTable(true);
        defaultInstance.initFields();
    }

    private final ByteString unknownFields;
    private List<ExpectToActual> expectToActuals_;
    private byte memoizedIsInitialized = -1;
    private int memoizedSerializedSize = -1;

    // Use ExpectActualTable.newBuilder() to construct.
    private ExpectActualTable(GeneratedMessageLite.Builder builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
    }
    private ExpectActualTable(boolean noInit) {
        this.unknownFields = ByteString.EMPTY;
    }

    private ExpectActualTable(
            CodedInputStream input,
            ExtensionRegistryLite extensionRegistry)
            throws InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        ByteString.Output unknownFieldsOutput =
                ByteString.newOutput();
        CodedOutputStream unknownFieldsCodedOutput =
                CodedOutputStream.newInstance(
                        unknownFieldsOutput, 1);
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    default: {
                        if (!parseUnknownField(input, unknownFieldsCodedOutput,
                                extensionRegistry, tag)) {
                            done = true;
                        }
                        break;
                    }
                    case 10: {
                        if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                            expectToActuals_ = new ArrayList<ExpectToActual>();
                            mutable_bitField0_ |= 0x00000001;
                        }
                        expectToActuals_.add(input.readMessage(ExpectToActual.PARSER, extensionRegistry));
                        break;
                    }
                }
            }
        } catch (InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (IOException e) {
            throw new InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this);
        } finally {
            if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                expectToActuals_ = Collections.unmodifiableList(expectToActuals_);
            }
            try {
                unknownFieldsCodedOutput.flush();
            } catch (IOException e) {
                // Should not happen
            } finally {
                unknownFields = unknownFieldsOutput.toByteString();
            }
            makeExtensionsImmutable();
        }
    }

    public static ExpectActualTable getDefaultInstance() {
        return defaultInstance;
    }

    public static ExpectActualTable parseFrom(
            ByteString data)
            throws InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static ExpectActualTable parseFrom(
            ByteString data,
            ExtensionRegistryLite extensionRegistry)
            throws InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static ExpectActualTable parseFrom(byte[] data)
            throws InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static ExpectActualTable parseFrom(
            byte[] data,
            ExtensionRegistryLite extensionRegistry)
            throws InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static ExpectActualTable parseFrom(InputStream input)
            throws IOException {
        return PARSER.parseFrom(input);
    }

    public static ExpectActualTable parseFrom(
            InputStream input,
            ExtensionRegistryLite extensionRegistry)
            throws IOException {
        return PARSER.parseFrom(input, extensionRegistry);
    }

    public static ExpectActualTable parseDelimitedFrom(InputStream input)
            throws IOException {
        return PARSER.parseDelimitedFrom(input);
    }

    public static ExpectActualTable parseDelimitedFrom(
            InputStream input,
            ExtensionRegistryLite extensionRegistry)
            throws IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }

    public static ExpectActualTable parseFrom(
            CodedInputStream input)
            throws IOException {
        return PARSER.parseFrom(input);
    }

    public static ExpectActualTable parseFrom(
            CodedInputStream input,
            ExtensionRegistryLite extensionRegistry)
            throws IOException {
        return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() {
        return Builder.create();
    }

    public static Builder newBuilder(ExpectActualTable prototype) {
        return newBuilder().mergeFrom(prototype);
    }

    @Override
    public ExpectActualTable getDefaultInstanceForType() {
        return defaultInstance;
    }

    @Override
    public Parser<ExpectActualTable> getParserForType() {
        return PARSER;
    }

    /**
     * <code>repeated .org.jetbrains.kotlin.backend.common.serialization.proto.ExpectToActual expectToActuals = 1;</code>
     */
    @Override
    public List<ExpectToActual> getExpectToActualsList() {
        return expectToActuals_;
    }

    /**
     * <code>repeated .org.jetbrains.kotlin.backend.common.serialization.proto.ExpectToActual expectToActuals = 1;</code>
     */
    public List<? extends ExpectToActualOrBuilder>
    getExpectToActualsOrBuilderList() {
        return expectToActuals_;
    }

    /**
     * <code>repeated .org.jetbrains.kotlin.backend.common.serialization.proto.ExpectToActual expectToActuals = 1;</code>
     */
    @Override
    public int getExpectToActualsCount() {
        return expectToActuals_.size();
    }

    /**
     * <code>repeated .org.jetbrains.kotlin.backend.common.serialization.proto.ExpectToActual expectToActuals = 1;</code>
     */
    @Override
    public ExpectToActual getExpectToActuals(int index) {
        return expectToActuals_.get(index);
    }

    /**
     * <code>repeated .org.jetbrains.kotlin.backend.common.serialization.proto.ExpectToActual expectToActuals = 1;</code>
     */
    public ExpectToActualOrBuilder getExpectToActualsOrBuilder(
            int index) {
        return expectToActuals_.get(index);
    }

    private void initFields() {
        expectToActuals_ = Collections.emptyList();
    }

    @Override
    public boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        for (int i = 0; i < getExpectToActualsCount(); i++) {
            if (!getExpectToActuals(i).isInitialized()) {
                memoizedIsInitialized = 0;
                return false;
            }
        }
        memoizedIsInitialized = 1;
        return true;
    }

    @Override
    public void writeTo(CodedOutputStream output)
            throws IOException {
        getSerializedSize();
        for (int i = 0; i < expectToActuals_.size(); i++) {
            output.writeMessage(1, expectToActuals_.get(i));
        }
        output.writeRawBytes(unknownFields);
    }

    @Override
    public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        for (int i = 0; i < expectToActuals_.size(); i++) {
            size += CodedOutputStream
                    .computeMessageSize(1, expectToActuals_.get(i));
        }
        size += unknownFields.size();
        memoizedSerializedSize = size;
        return size;
    }

    @Override
    protected Object writeReplace()
            throws ObjectStreamException {
        return super.writeReplace();
    }

    @Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    @Override
    public Builder toBuilder() {
        return newBuilder(this);
    }

    /**
     * Protobuf type {@code org.jetbrains.kotlin.backend.common.serialization.proto.ExpectActualTable}
     */
    public static final class Builder extends
            GeneratedMessageLite.Builder<
                    ExpectActualTable, Builder>
            implements
            // @@protoc_insertion_point(builder_implements:org.jetbrains.kotlin.backend.common.serialization.proto.ExpectActualTable)
            ExpectActualTableOrBuilder {
        private int bitField0_;
        private List<ExpectToActual> expectToActuals_ =
                Collections.emptyList();

        // Construct using org.jetbrains.kotlin.backend.common.serialization.proto.ExpectActualTable.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private static Builder create() {
            return new Builder();
        }

        private void maybeForceBuilderInitialization() {
        }

        @Override
        public Builder clear() {
            super.clear();
            expectToActuals_ = Collections.emptyList();
            bitField0_ &= ~0x00000001;
            return this;
        }

        @Override
        public Builder clone() {
            return create().mergeFrom(buildPartial());
        }

        @Override
        public ExpectActualTable getDefaultInstanceForType() {
            return getDefaultInstance();
        }

        @Override
        public ExpectActualTable build() {
            ExpectActualTable result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @Override
        public ExpectActualTable buildPartial() {
            ExpectActualTable result = new ExpectActualTable(this);
            int from_bitField0_ = bitField0_;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                expectToActuals_ = Collections.unmodifiableList(expectToActuals_);
                bitField0_ &= ~0x00000001;
            }
            result.expectToActuals_ = expectToActuals_;
            return result;
        }

        @Override
        public Builder mergeFrom(ExpectActualTable other) {
            if (other == getDefaultInstance())
                return this;
            if (!other.expectToActuals_.isEmpty()) {
                if (expectToActuals_.isEmpty()) {
                    expectToActuals_ = other.expectToActuals_;
                    bitField0_ &= ~0x00000001;
                } else {
                    ensureExpectToActualsIsMutable();
                    expectToActuals_.addAll(other.expectToActuals_);
                }

            }
            setUnknownFields(
                    getUnknownFields().concat(other.unknownFields));
            return this;
        }

        @Override
        public boolean isInitialized() {
            for (int i = 0; i < getExpectToActualsCount(); i++) {
                if (!getExpectToActuals(i).isInitialized()) {

                    return false;
                }
            }
            return true;
        }

        @Override
        public Builder mergeFrom(
                CodedInputStream input,
                ExtensionRegistryLite extensionRegistry)
                throws IOException {
            ExpectActualTable parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (InvalidProtocolBufferException e) {
                parsedMessage = (ExpectActualTable) e.getUnfinishedMessage();
                throw e;
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        private void ensureExpectToActualsIsMutable() {
            if (!((bitField0_ & 0x00000001) == 0x00000001)) {
                expectToActuals_ = new ArrayList<ExpectToActual>(expectToActuals_);
                bitField0_ |= 0x00000001;
            }
        }

        /**
         * <code>repeated .org.jetbrains.kotlin.backend.common.serialization.proto.ExpectToActual expectToActuals = 1;</code>
         */
        @Override
        public List<ExpectToActual> getExpectToActualsList() {
            return Collections.unmodifiableList(expectToActuals_);
        }

        /**
         * <code>repeated .org.jetbrains.kotlin.backend.common.serialization.proto.ExpectToActual expectToActuals = 1;</code>
         */
        @Override
        public int getExpectToActualsCount() {
            return expectToActuals_.size();
        }

        /**
         * <code>repeated .org.jetbrains.kotlin.backend.common.serialization.proto.ExpectToActual expectToActuals = 1;</code>
         */
        @Override
        public ExpectToActual getExpectToActuals(int index) {
            return expectToActuals_.get(index);
        }

        /**
         * <code>repeated .org.jetbrains.kotlin.backend.common.serialization.proto.ExpectToActual expectToActuals = 1;</code>
         */
        public Builder setExpectToActuals(
                int index, ExpectToActual value) {
            if (value == null) {
                throw new NullPointerException();
            }
            ensureExpectToActualsIsMutable();
            expectToActuals_.set(index, value);

            return this;
        }

        /**
         * <code>repeated .org.jetbrains.kotlin.backend.common.serialization.proto.ExpectToActual expectToActuals = 1;</code>
         */
        public Builder setExpectToActuals(
                int index, ExpectToActual.Builder builderForValue) {
            ensureExpectToActualsIsMutable();
            expectToActuals_.set(index, builderForValue.build());

            return this;
        }

        /**
         * <code>repeated .org.jetbrains.kotlin.backend.common.serialization.proto.ExpectToActual expectToActuals = 1;</code>
         */
        public Builder addExpectToActuals(ExpectToActual value) {
            if (value == null) {
                throw new NullPointerException();
            }
            ensureExpectToActualsIsMutable();
            expectToActuals_.add(value);

            return this;
        }

        /**
         * <code>repeated .org.jetbrains.kotlin.backend.common.serialization.proto.ExpectToActual expectToActuals = 1;</code>
         */
        public Builder addExpectToActuals(
                int index, ExpectToActual value) {
            if (value == null) {
                throw new NullPointerException();
            }
            ensureExpectToActualsIsMutable();
            expectToActuals_.add(index, value);

            return this;
        }

        /**
         * <code>repeated .org.jetbrains.kotlin.backend.common.serialization.proto.ExpectToActual expectToActuals = 1;</code>
         */
        public Builder addExpectToActuals(
                ExpectToActual.Builder builderForValue) {
            ensureExpectToActualsIsMutable();
            expectToActuals_.add(builderForValue.build());

            return this;
        }

        /**
         * <code>repeated .org.jetbrains.kotlin.backend.common.serialization.proto.ExpectToActual expectToActuals = 1;</code>
         */
        public Builder addExpectToActuals(
                int index, ExpectToActual.Builder builderForValue) {
            ensureExpectToActualsIsMutable();
            expectToActuals_.add(index, builderForValue.build());

            return this;
        }

        /**
         * <code>repeated .org.jetbrains.kotlin.backend.common.serialization.proto.ExpectToActual expectToActuals = 1;</code>
         */
        public Builder addAllExpectToActuals(
                Iterable<? extends ExpectToActual> values) {
            ensureExpectToActualsIsMutable();
            addAll(
                    values, expectToActuals_);

            return this;
        }

        /**
         * <code>repeated .org.jetbrains.kotlin.backend.common.serialization.proto.ExpectToActual expectToActuals = 1;</code>
         */
        public Builder clearExpectToActuals() {
            expectToActuals_ = Collections.emptyList();
            bitField0_ &= ~0x00000001;

            return this;
        }

        /**
         * <code>repeated .org.jetbrains.kotlin.backend.common.serialization.proto.ExpectToActual expectToActuals = 1;</code>
         */
        public Builder removeExpectToActuals(int index) {
            ensureExpectToActualsIsMutable();
            expectToActuals_.remove(index);

            return this;
        }

        // @@protoc_insertion_point(builder_scope:org.jetbrains.kotlin.backend.common.serialization.proto.ExpectActualTable)
    }

    // @@protoc_insertion_point(class_scope:org.jetbrains.kotlin.backend.common.serialization.proto.ExpectActualTable)
}
