// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compiler/ir/serialization.common/src/KotlinIr.proto

package org.jetbrains.kotlin.backend.common.serialization.proto;

import org.jetbrains.kotlin.protobuf.AbstractParser;
import org.jetbrains.kotlin.protobuf.ByteString;
import org.jetbrains.kotlin.protobuf.CodedInputStream;
import org.jetbrains.kotlin.protobuf.CodedOutputStream;
import org.jetbrains.kotlin.protobuf.ExtensionRegistryLite;
import org.jetbrains.kotlin.protobuf.GeneratedMessageLite;
import org.jetbrains.kotlin.protobuf.InvalidProtocolBufferException;
import org.jetbrains.kotlin.protobuf.Parser;

import java.io.IOException;
import java.io.InputStream;
import java.io.ObjectStreamException;

/**
 * Protobuf type {@code org.jetbrains.kotlin.backend.common.serialization.proto.FileLocalIdSignature}
 */
public final class FileLocalIdSignature extends
        GeneratedMessageLite implements
        // @@protoc_insertion_point(message_implements:org.jetbrains.kotlin.backend.common.serialization.proto.FileLocalIdSignature)
        FileLocalIdSignatureOrBuilder {
    public static final int CONTAINER_FIELD_NUMBER = 1;
    public static final int LOCAL_ID_FIELD_NUMBER = 2;
    public static final int DEBUG_INFO_FIELD_NUMBER = 3;
    private static final FileLocalIdSignature defaultInstance;
    private static final long serialVersionUID = 0L;
    public static Parser<FileLocalIdSignature> PARSER =
            new AbstractParser<FileLocalIdSignature>() {
                @Override
                public FileLocalIdSignature parsePartialFrom(
                        CodedInputStream input,
                        ExtensionRegistryLite extensionRegistry)
                        throws InvalidProtocolBufferException {
                    return new FileLocalIdSignature(input, extensionRegistry);
                }
            };

    static {
        defaultInstance = new FileLocalIdSignature(true);
        defaultInstance.initFields();
    }

    private final ByteString unknownFields;
    private int bitField0_;
    private int container_;
    private long localId_;
    private int debugInfo_;
    private byte memoizedIsInitialized = -1;
    private int memoizedSerializedSize = -1;

    // Use FileLocalIdSignature.newBuilder() to construct.
    private FileLocalIdSignature(GeneratedMessageLite.Builder builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
    }
    private FileLocalIdSignature(boolean noInit) {
        this.unknownFields = ByteString.EMPTY;
    }

    private FileLocalIdSignature(
            CodedInputStream input,
            ExtensionRegistryLite extensionRegistry)
            throws InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        ByteString.Output unknownFieldsOutput =
                ByteString.newOutput();
        CodedOutputStream unknownFieldsCodedOutput =
                CodedOutputStream.newInstance(
                        unknownFieldsOutput, 1);
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    default: {
                        if (!parseUnknownField(input, unknownFieldsCodedOutput,
                                extensionRegistry, tag)) {
                            done = true;
                        }
                        break;
                    }
                    case 8: {
                        bitField0_ |= 0x00000001;
                        container_ = input.readInt32();
                        break;
                    }
                    case 16: {
                        bitField0_ |= 0x00000002;
                        localId_ = input.readInt64();
                        break;
                    }
                    case 24: {
                        bitField0_ |= 0x00000004;
                        debugInfo_ = input.readInt32();
                        break;
                    }
                }
            }
        } catch (InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (IOException e) {
            throw new InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this);
        } finally {
            try {
                unknownFieldsCodedOutput.flush();
            } catch (IOException e) {
                // Should not happen
            } finally {
                unknownFields = unknownFieldsOutput.toByteString();
            }
            makeExtensionsImmutable();
        }
    }

    public static FileLocalIdSignature getDefaultInstance() {
        return defaultInstance;
    }

    public static FileLocalIdSignature parseFrom(
            ByteString data)
            throws InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static FileLocalIdSignature parseFrom(
            ByteString data,
            ExtensionRegistryLite extensionRegistry)
            throws InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static FileLocalIdSignature parseFrom(byte[] data)
            throws InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static FileLocalIdSignature parseFrom(
            byte[] data,
            ExtensionRegistryLite extensionRegistry)
            throws InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static FileLocalIdSignature parseFrom(InputStream input)
            throws IOException {
        return PARSER.parseFrom(input);
    }

    public static FileLocalIdSignature parseFrom(
            InputStream input,
            ExtensionRegistryLite extensionRegistry)
            throws IOException {
        return PARSER.parseFrom(input, extensionRegistry);
    }

    public static FileLocalIdSignature parseDelimitedFrom(InputStream input)
            throws IOException {
        return PARSER.parseDelimitedFrom(input);
    }

    public static FileLocalIdSignature parseDelimitedFrom(
            InputStream input,
            ExtensionRegistryLite extensionRegistry)
            throws IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }

    public static FileLocalIdSignature parseFrom(
            CodedInputStream input)
            throws IOException {
        return PARSER.parseFrom(input);
    }

    public static FileLocalIdSignature parseFrom(
            CodedInputStream input,
            ExtensionRegistryLite extensionRegistry)
            throws IOException {
        return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() {
        return Builder.create();
    }

    public static Builder newBuilder(FileLocalIdSignature prototype) {
        return newBuilder().mergeFrom(prototype);
    }

    @Override
    public FileLocalIdSignature getDefaultInstanceForType() {
        return defaultInstance;
    }

    @Override
    public Parser<FileLocalIdSignature> getParserForType() {
        return PARSER;
    }

    /**
     * <code>required int32 container = 1;</code>
     */
    @Override
    public boolean hasContainer() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
    }

    /**
     * <code>required int32 container = 1;</code>
     */
    @Override
    public int getContainer() {
        return container_;
    }

    /**
     * <code>required int64 local_id = 2;</code>
     */
    @Override
    public boolean hasLocalId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
    }

    /**
     * <code>required int64 local_id = 2;</code>
     */
    @Override
    public long getLocalId() {
        return localId_;
    }

    /**
     * <code>optional int32 debug_info = 3;</code>
     */
    @Override
    public boolean hasDebugInfo() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
    }

    /**
     * <code>optional int32 debug_info = 3;</code>
     */
    @Override
    public int getDebugInfo() {
        return debugInfo_;
    }

    private void initFields() {
        container_ = 0;
        localId_ = 0L;
        debugInfo_ = 0;
    }

    @Override
    public boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasContainer()) {
            memoizedIsInitialized = 0;
            return false;
        }
        if (!hasLocalId()) {
            memoizedIsInitialized = 0;
            return false;
        }
        memoizedIsInitialized = 1;
        return true;
    }

    @Override
    public void writeTo(CodedOutputStream output)
            throws IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
            output.writeInt32(1, container_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
            output.writeInt64(2, localId_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
            output.writeInt32(3, debugInfo_);
        }
        output.writeRawBytes(unknownFields);
    }

    @Override
    public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
            size += CodedOutputStream
                    .computeInt32Size(1, container_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
            size += CodedOutputStream
                    .computeInt64Size(2, localId_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
            size += CodedOutputStream
                    .computeInt32Size(3, debugInfo_);
        }
        size += unknownFields.size();
        memoizedSerializedSize = size;
        return size;
    }

    @Override
    protected Object writeReplace()
            throws ObjectStreamException {
        return super.writeReplace();
    }

    @Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    @Override
    public Builder toBuilder() {
        return newBuilder(this);
    }

    /**
     * Protobuf type {@code org.jetbrains.kotlin.backend.common.serialization.proto.FileLocalIdSignature}
     */
    public static final class Builder extends
            GeneratedMessageLite.Builder<
                    FileLocalIdSignature, Builder>
            implements
            // @@protoc_insertion_point(builder_implements:org.jetbrains.kotlin.backend.common.serialization.proto.FileLocalIdSignature)
            FileLocalIdSignatureOrBuilder {
        private int bitField0_;
        private int container_;
        private long localId_;
        private int debugInfo_;

        // Construct using org.jetbrains.kotlin.backend.common.serialization.proto.FileLocalIdSignature.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private static Builder create() {
            return new Builder();
        }

        private void maybeForceBuilderInitialization() {
        }

        @Override
        public Builder clear() {
            super.clear();
            container_ = 0;
            bitField0_ &= ~0x00000001;
            localId_ = 0L;
            bitField0_ &= ~0x00000002;
            debugInfo_ = 0;
            bitField0_ &= ~0x00000004;
            return this;
        }

        @Override
        public Builder clone() {
            return create().mergeFrom(buildPartial());
        }

        @Override
        public FileLocalIdSignature getDefaultInstanceForType() {
            return getDefaultInstance();
        }

        @Override
        public FileLocalIdSignature build() {
            FileLocalIdSignature result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @Override
        public FileLocalIdSignature buildPartial() {
            FileLocalIdSignature result = new FileLocalIdSignature(this);
            int from_bitField0_ = bitField0_;
            int to_bitField0_ = 0;
            if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                to_bitField0_ |= 0x00000001;
            }
            result.container_ = container_;
            if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                to_bitField0_ |= 0x00000002;
            }
            result.localId_ = localId_;
            if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
                to_bitField0_ |= 0x00000004;
            }
            result.debugInfo_ = debugInfo_;
            result.bitField0_ = to_bitField0_;
            return result;
        }

        @Override
        public Builder mergeFrom(FileLocalIdSignature other) {
            if (other == getDefaultInstance())
                return this;
            if (other.hasContainer()) {
                setContainer(other.getContainer());
            }
            if (other.hasLocalId()) {
                setLocalId(other.getLocalId());
            }
            if (other.hasDebugInfo()) {
                setDebugInfo(other.getDebugInfo());
            }
            setUnknownFields(
                    getUnknownFields().concat(other.unknownFields));
            return this;
        }

        @Override
        public boolean isInitialized() {
            if (!hasContainer()) {

                return false;
            }
            if (!hasLocalId()) {

                return false;
            }
            return true;
        }

        @Override
        public Builder mergeFrom(
                CodedInputStream input,
                ExtensionRegistryLite extensionRegistry)
                throws IOException {
            FileLocalIdSignature parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (InvalidProtocolBufferException e) {
                parsedMessage = (FileLocalIdSignature) e.getUnfinishedMessage();
                throw e;
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        /**
         * <code>required int32 container = 1;</code>
         */
        @Override
        public boolean hasContainer() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <code>required int32 container = 1;</code>
         */
        @Override
        public int getContainer() {
            return container_;
        }

        /**
         * <code>required int32 container = 1;</code>
         */
        public Builder setContainer(int value) {
            bitField0_ |= 0x00000001;
            container_ = value;

            return this;
        }

        /**
         * <code>required int32 container = 1;</code>
         */
        public Builder clearContainer() {
            bitField0_ &= ~0x00000001;
            container_ = 0;

            return this;
        }

        /**
         * <code>required int64 local_id = 2;</code>
         */
        @Override
        public boolean hasLocalId() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        /**
         * <code>required int64 local_id = 2;</code>
         */
        @Override
        public long getLocalId() {
            return localId_;
        }

        /**
         * <code>required int64 local_id = 2;</code>
         */
        public Builder setLocalId(long value) {
            bitField0_ |= 0x00000002;
            localId_ = value;

            return this;
        }

        /**
         * <code>required int64 local_id = 2;</code>
         */
        public Builder clearLocalId() {
            bitField0_ &= ~0x00000002;
            localId_ = 0L;

            return this;
        }

        /**
         * <code>optional int32 debug_info = 3;</code>
         */
        @Override
        public boolean hasDebugInfo() {
            return ((bitField0_ & 0x00000004) == 0x00000004);
        }

        /**
         * <code>optional int32 debug_info = 3;</code>
         */
        @Override
        public int getDebugInfo() {
            return debugInfo_;
        }

        /**
         * <code>optional int32 debug_info = 3;</code>
         */
        public Builder setDebugInfo(int value) {
            bitField0_ |= 0x00000004;
            debugInfo_ = value;

            return this;
        }

        /**
         * <code>optional int32 debug_info = 3;</code>
         */
        public Builder clearDebugInfo() {
            bitField0_ &= ~0x00000004;
            debugInfo_ = 0;

            return this;
        }

        // @@protoc_insertion_point(builder_scope:org.jetbrains.kotlin.backend.common.serialization.proto.FileLocalIdSignature)
    }

    // @@protoc_insertion_point(class_scope:org.jetbrains.kotlin.backend.common.serialization.proto.FileLocalIdSignature)
}
