// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compiler/ir/serialization.common/src/KotlinIr.proto

package org.jetbrains.kotlin.backend.common.serialization.proto;

import org.jetbrains.kotlin.protobuf.AbstractParser;
import org.jetbrains.kotlin.protobuf.ByteString;
import org.jetbrains.kotlin.protobuf.CodedInputStream;
import org.jetbrains.kotlin.protobuf.CodedOutputStream;
import org.jetbrains.kotlin.protobuf.ExtensionRegistryLite;
import org.jetbrains.kotlin.protobuf.GeneratedMessageLite;
import org.jetbrains.kotlin.protobuf.InvalidProtocolBufferException;
import org.jetbrains.kotlin.protobuf.Parser;

import java.io.IOException;
import java.io.InputStream;
import java.io.ObjectStreamException;

/**
 * Protobuf type {@code org.jetbrains.kotlin.backend.common.serialization.proto.FileWrappedIdSignature}
 */
public final class FileWrappedIdSignature extends
        GeneratedMessageLite implements
        // @@protoc_insertion_point(message_implements:org.jetbrains.kotlin.backend.common.serialization.proto.FileWrappedIdSignature)
        FileWrappedIdSignatureOrBuilder {
    public static final int DELEGATE_FIELD_NUMBER = 1;
    public static final int FILE_FIELD_NUMBER = 2;
    private static final FileWrappedIdSignature defaultInstance;
    private static final long serialVersionUID = 0L;
    public static Parser<FileWrappedIdSignature> PARSER =
            new AbstractParser<FileWrappedIdSignature>() {
                @Override
                public FileWrappedIdSignature parsePartialFrom(
                        CodedInputStream input,
                        ExtensionRegistryLite extensionRegistry)
                        throws InvalidProtocolBufferException {
                    return new FileWrappedIdSignature(input, extensionRegistry);
                }
            };

    static {
        defaultInstance = new FileWrappedIdSignature(true);
        defaultInstance.initFields();
    }

    private final ByteString unknownFields;
    private int bitField0_;
    private IdSignature delegate_;
    private int file_;
    private byte memoizedIsInitialized = -1;
    private int memoizedSerializedSize = -1;

    // Use FileWrappedIdSignature.newBuilder() to construct.
    private FileWrappedIdSignature(GeneratedMessageLite.Builder builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
    }

    private FileWrappedIdSignature(boolean noInit) {
        this.unknownFields = ByteString.EMPTY;
    }

    private FileWrappedIdSignature(
            CodedInputStream input,
            ExtensionRegistryLite extensionRegistry)
            throws InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        ByteString.Output unknownFieldsOutput =
                ByteString.newOutput();
        CodedOutputStream unknownFieldsCodedOutput =
                CodedOutputStream.newInstance(
                        unknownFieldsOutput, 1);
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    default: {
                        if (!parseUnknownField(input, unknownFieldsCodedOutput,
                                extensionRegistry, tag)) {
                            done = true;
                        }
                        break;
                    }
                    case 10: {
                        IdSignature.Builder subBuilder = null;
                        if (((bitField0_ & 0x00000001) == 0x00000001)) {
                            subBuilder = delegate_.toBuilder();
                        }
                        delegate_ = input.readMessage(IdSignature.PARSER, extensionRegistry);
                        if (subBuilder != null) {
                            subBuilder.mergeFrom(delegate_);
                            delegate_ = subBuilder.buildPartial();
                        }
                        bitField0_ |= 0x00000001;
                        break;
                    }
                    case 16: {
                        bitField0_ |= 0x00000002;
                        file_ = input.readInt32();
                        break;
                    }
                }
            }
        } catch (InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (IOException e) {
            throw new InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this);
        } finally {
            try {
                unknownFieldsCodedOutput.flush();
            } catch (IOException e) {
                // Should not happen
            } finally {
                unknownFields = unknownFieldsOutput.toByteString();
            }
            makeExtensionsImmutable();
        }
    }

    public static FileWrappedIdSignature getDefaultInstance() {
        return defaultInstance;
    }

    public static FileWrappedIdSignature parseFrom(
            ByteString data)
            throws InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static FileWrappedIdSignature parseFrom(
            ByteString data,
            ExtensionRegistryLite extensionRegistry)
            throws InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static FileWrappedIdSignature parseFrom(byte[] data)
            throws InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static FileWrappedIdSignature parseFrom(
            byte[] data,
            ExtensionRegistryLite extensionRegistry)
            throws InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static FileWrappedIdSignature parseFrom(InputStream input)
            throws IOException {
        return PARSER.parseFrom(input);
    }

    public static FileWrappedIdSignature parseFrom(
            InputStream input,
            ExtensionRegistryLite extensionRegistry)
            throws IOException {
        return PARSER.parseFrom(input, extensionRegistry);
    }

    public static FileWrappedIdSignature parseDelimitedFrom(InputStream input)
            throws IOException {
        return PARSER.parseDelimitedFrom(input);
    }

    public static FileWrappedIdSignature parseDelimitedFrom(
            InputStream input,
            ExtensionRegistryLite extensionRegistry)
            throws IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }

    public static FileWrappedIdSignature parseFrom(
            CodedInputStream input)
            throws IOException {
        return PARSER.parseFrom(input);
    }

    public static FileWrappedIdSignature parseFrom(
            CodedInputStream input,
            ExtensionRegistryLite extensionRegistry)
            throws IOException {
        return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() {
        return Builder.create();
    }

    public static Builder newBuilder(FileWrappedIdSignature prototype) {
        return newBuilder().mergeFrom(prototype);
    }

    @Override
    public FileWrappedIdSignature getDefaultInstanceForType() {
        return defaultInstance;
    }

    @Override
    public Parser<FileWrappedIdSignature> getParserForType() {
        return PARSER;
    }

    /**
     * <code>required .org.jetbrains.kotlin.backend.common.serialization.proto.IdSignature delegate = 1;</code>
     */
    @Override
    public boolean hasDelegate() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
    }

    /**
     * <code>required .org.jetbrains.kotlin.backend.common.serialization.proto.IdSignature delegate = 1;</code>
     */
    @Override
    public IdSignature getDelegate() {
        return delegate_;
    }

    /**
     * <code>required int32 file = 2;</code>
     */
    @Override
    public boolean hasFile() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
    }

    /**
     * <code>required int32 file = 2;</code>
     */
    @Override
    public int getFile() {
        return file_;
    }

    private void initFields() {
        delegate_ = IdSignature.getDefaultInstance();
        file_ = 0;
    }

    @Override
    public boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasDelegate()) {
            memoizedIsInitialized = 0;
            return false;
        }
        if (!hasFile()) {
            memoizedIsInitialized = 0;
            return false;
        }
        if (!getDelegate().isInitialized()) {
            memoizedIsInitialized = 0;
            return false;
        }
        memoizedIsInitialized = 1;
        return true;
    }

    @Override
    public void writeTo(CodedOutputStream output)
            throws IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
            output.writeMessage(1, delegate_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
            output.writeInt32(2, file_);
        }
        output.writeRawBytes(unknownFields);
    }

    @Override
    public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
            size += CodedOutputStream
                    .computeMessageSize(1, delegate_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
            size += CodedOutputStream
                    .computeInt32Size(2, file_);
        }
        size += unknownFields.size();
        memoizedSerializedSize = size;
        return size;
    }

    @Override
    protected Object writeReplace()
            throws ObjectStreamException {
        return super.writeReplace();
    }

    @Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    @Override
    public Builder toBuilder() {
        return newBuilder(this);
    }

    /**
     * Protobuf type {@code org.jetbrains.kotlin.backend.common.serialization.proto.FileWrappedIdSignature}
     */
    public static final class Builder extends
            GeneratedMessageLite.Builder<
                    FileWrappedIdSignature, Builder>
            implements
            // @@protoc_insertion_point(builder_implements:org.jetbrains.kotlin.backend.common.serialization.proto.FileWrappedIdSignature)
            FileWrappedIdSignatureOrBuilder {
        private int bitField0_;
        private IdSignature delegate_ = IdSignature.getDefaultInstance();
        private int file_;

        // Construct using org.jetbrains.kotlin.backend.common.serialization.proto.FileWrappedIdSignature.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private static Builder create() {
            return new Builder();
        }

        private void maybeForceBuilderInitialization() {
        }

        @Override
        public Builder clear() {
            super.clear();
            delegate_ = IdSignature.getDefaultInstance();
            bitField0_ &= ~0x00000001;
            file_ = 0;
            bitField0_ &= ~0x00000002;
            return this;
        }

        @Override
        public Builder clone() {
            return create().mergeFrom(buildPartial());
        }

        @Override
        public FileWrappedIdSignature getDefaultInstanceForType() {
            return getDefaultInstance();
        }

        @Override
        public FileWrappedIdSignature build() {
            FileWrappedIdSignature result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @Override
        public FileWrappedIdSignature buildPartial() {
            FileWrappedIdSignature result = new FileWrappedIdSignature(this);
            int from_bitField0_ = bitField0_;
            int to_bitField0_ = 0;
            if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                to_bitField0_ |= 0x00000001;
            }
            result.delegate_ = delegate_;
            if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                to_bitField0_ |= 0x00000002;
            }
            result.file_ = file_;
            result.bitField0_ = to_bitField0_;
            return result;
        }

        @Override
        public Builder mergeFrom(FileWrappedIdSignature other) {
            if (other == getDefaultInstance())
                return this;
            if (other.hasDelegate()) {
                mergeDelegate(other.getDelegate());
            }
            if (other.hasFile()) {
                setFile(other.getFile());
            }
            setUnknownFields(
                    getUnknownFields().concat(other.unknownFields));
            return this;
        }

        @Override
        public boolean isInitialized() {
            if (!hasDelegate()) {

                return false;
            }
            if (!hasFile()) {

                return false;
            }
            if (!getDelegate().isInitialized()) {

                return false;
            }
            return true;
        }

        @Override
        public Builder mergeFrom(
                CodedInputStream input,
                ExtensionRegistryLite extensionRegistry)
                throws IOException {
            FileWrappedIdSignature parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (InvalidProtocolBufferException e) {
                parsedMessage = (FileWrappedIdSignature) e.getUnfinishedMessage();
                throw e;
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        /**
         * <code>required .org.jetbrains.kotlin.backend.common.serialization.proto.IdSignature delegate = 1;</code>
         */
        @Override
        public boolean hasDelegate() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <code>required .org.jetbrains.kotlin.backend.common.serialization.proto.IdSignature delegate = 1;</code>
         */
        @Override
        public IdSignature getDelegate() {
            return delegate_;
        }

        /**
         * <code>required .org.jetbrains.kotlin.backend.common.serialization.proto.IdSignature delegate = 1;</code>
         */
        public Builder setDelegate(IdSignature value) {
            if (value == null) {
                throw new NullPointerException();
            }
            delegate_ = value;

            bitField0_ |= 0x00000001;
            return this;
        }

        /**
         * <code>required .org.jetbrains.kotlin.backend.common.serialization.proto.IdSignature delegate = 1;</code>
         */
        public Builder setDelegate(
                IdSignature.Builder builderForValue) {
            delegate_ = builderForValue.build();

            bitField0_ |= 0x00000001;
            return this;
        }

        /**
         * <code>required .org.jetbrains.kotlin.backend.common.serialization.proto.IdSignature delegate = 1;</code>
         */
        public Builder mergeDelegate(IdSignature value) {
            if (((bitField0_ & 0x00000001) == 0x00000001) &&
                    delegate_ != IdSignature.getDefaultInstance()) {
                delegate_ =
                        IdSignature.newBuilder(delegate_).mergeFrom(value).buildPartial();
            } else {
                delegate_ = value;
            }

            bitField0_ |= 0x00000001;
            return this;
        }

        /**
         * <code>required .org.jetbrains.kotlin.backend.common.serialization.proto.IdSignature delegate = 1;</code>
         */
        public Builder clearDelegate() {
            delegate_ = IdSignature.getDefaultInstance();

            bitField0_ &= ~0x00000001;
            return this;
        }

        /**
         * <code>required int32 file = 2;</code>
         */
        @Override
        public boolean hasFile() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        /**
         * <code>required int32 file = 2;</code>
         */
        @Override
        public int getFile() {
            return file_;
        }

        /**
         * <code>required int32 file = 2;</code>
         */
        public Builder setFile(int value) {
            bitField0_ |= 0x00000002;
            file_ = value;

            return this;
        }

        /**
         * <code>required int32 file = 2;</code>
         */
        public Builder clearFile() {
            bitField0_ &= ~0x00000002;
            file_ = 0;

            return this;
        }

        // @@protoc_insertion_point(builder_scope:org.jetbrains.kotlin.backend.common.serialization.proto.FileWrappedIdSignature)
    }

    // @@protoc_insertion_point(class_scope:org.jetbrains.kotlin.backend.common.serialization.proto.FileWrappedIdSignature)
}
