// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compiler/ir/serialization.common/src/KotlinIr.proto

package org.jetbrains.kotlin.backend.common.serialization.proto;

import org.jetbrains.kotlin.protobuf.AbstractParser;
import org.jetbrains.kotlin.protobuf.ByteString;
import org.jetbrains.kotlin.protobuf.CodedInputStream;
import org.jetbrains.kotlin.protobuf.CodedOutputStream;
import org.jetbrains.kotlin.protobuf.ExtensionRegistryLite;
import org.jetbrains.kotlin.protobuf.GeneratedMessageLite;
import org.jetbrains.kotlin.protobuf.InvalidProtocolBufferException;
import org.jetbrains.kotlin.protobuf.Parser;

import java.io.IOException;
import java.io.InputStream;
import java.io.ObjectStreamException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/**
 * Protobuf type {@code org.jetbrains.kotlin.backend.common.serialization.proto.IrBlock}
 */
public final class IrBlock extends
        GeneratedMessageLite implements
        // @@protoc_insertion_point(message_implements:org.jetbrains.kotlin.backend.common.serialization.proto.IrBlock)
        IrBlockOrBuilder {
    public static final int STATEMENT_FIELD_NUMBER = 1;
    public static final int ORIGIN_NAME_FIELD_NUMBER = 2;
    private static final IrBlock defaultInstance;
    private static final long serialVersionUID = 0L;
    public static Parser<IrBlock> PARSER =
            new AbstractParser<IrBlock>() {
                @Override
                public IrBlock parsePartialFrom(
                        CodedInputStream input,
                        ExtensionRegistryLite extensionRegistry)
                        throws InvalidProtocolBufferException {
                    return new IrBlock(input, extensionRegistry);
                }
            };

    static {
        defaultInstance = new IrBlock(true);
        defaultInstance.initFields();
    }

    private final ByteString unknownFields;
    private int bitField0_;
    private List<IrStatement> statement_;
    private int originName_;
    private byte memoizedIsInitialized = -1;
    private int memoizedSerializedSize = -1;

    // Use IrBlock.newBuilder() to construct.
    private IrBlock(GeneratedMessageLite.Builder builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
    }

    private IrBlock(boolean noInit) {
        this.unknownFields = ByteString.EMPTY;
    }

    private IrBlock(
            CodedInputStream input,
            ExtensionRegistryLite extensionRegistry)
            throws InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        ByteString.Output unknownFieldsOutput =
                ByteString.newOutput();
        CodedOutputStream unknownFieldsCodedOutput =
                CodedOutputStream.newInstance(
                        unknownFieldsOutput, 1);
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    default: {
                        if (!parseUnknownField(input, unknownFieldsCodedOutput,
                                extensionRegistry, tag)) {
                            done = true;
                        }
                        break;
                    }
                    case 10: {
                        if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                            statement_ = new ArrayList<IrStatement>();
                            mutable_bitField0_ |= 0x00000001;
                        }
                        statement_.add(input.readMessage(IrStatement.PARSER, extensionRegistry));
                        break;
                    }
                    case 16: {
                        bitField0_ |= 0x00000001;
                        originName_ = input.readInt32();
                        break;
                    }
                }
            }
        } catch (InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (IOException e) {
            throw new InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this);
        } finally {
            if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                statement_ = Collections.unmodifiableList(statement_);
            }
            try {
                unknownFieldsCodedOutput.flush();
            } catch (IOException e) {
                // Should not happen
            } finally {
                unknownFields = unknownFieldsOutput.toByteString();
            }
            makeExtensionsImmutable();
        }
    }

    public static IrBlock getDefaultInstance() {
        return defaultInstance;
    }

    public static IrBlock parseFrom(
            ByteString data)
            throws InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static IrBlock parseFrom(
            ByteString data,
            ExtensionRegistryLite extensionRegistry)
            throws InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static IrBlock parseFrom(byte[] data)
            throws InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static IrBlock parseFrom(
            byte[] data,
            ExtensionRegistryLite extensionRegistry)
            throws InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static IrBlock parseFrom(InputStream input)
            throws IOException {
        return PARSER.parseFrom(input);
    }

    public static IrBlock parseFrom(
            InputStream input,
            ExtensionRegistryLite extensionRegistry)
            throws IOException {
        return PARSER.parseFrom(input, extensionRegistry);
    }

    public static IrBlock parseDelimitedFrom(InputStream input)
            throws IOException {
        return PARSER.parseDelimitedFrom(input);
    }

    public static IrBlock parseDelimitedFrom(
            InputStream input,
            ExtensionRegistryLite extensionRegistry)
            throws IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }

    public static IrBlock parseFrom(
            CodedInputStream input)
            throws IOException {
        return PARSER.parseFrom(input);
    }

    public static IrBlock parseFrom(
            CodedInputStream input,
            ExtensionRegistryLite extensionRegistry)
            throws IOException {
        return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() {
        return Builder.create();
    }

    public static Builder newBuilder(IrBlock prototype) {
        return newBuilder().mergeFrom(prototype);
    }

    @Override
    public IrBlock getDefaultInstanceForType() {
        return defaultInstance;
    }

    @Override
    public Parser<IrBlock> getParserForType() {
        return PARSER;
    }

    /**
     * <code>repeated .org.jetbrains.kotlin.backend.common.serialization.proto.IrStatement statement = 1;</code>
     */
    @Override
    public List<IrStatement> getStatementList() {
        return statement_;
    }

    /**
     * <code>repeated .org.jetbrains.kotlin.backend.common.serialization.proto.IrStatement statement = 1;</code>
     */
    public List<? extends IrStatementOrBuilder>
    getStatementOrBuilderList() {
        return statement_;
    }

    /**
     * <code>repeated .org.jetbrains.kotlin.backend.common.serialization.proto.IrStatement statement = 1;</code>
     */
    @Override
    public int getStatementCount() {
        return statement_.size();
    }

    /**
     * <code>repeated .org.jetbrains.kotlin.backend.common.serialization.proto.IrStatement statement = 1;</code>
     */
    @Override
    public IrStatement getStatement(int index) {
        return statement_.get(index);
    }

    /**
     * <code>repeated .org.jetbrains.kotlin.backend.common.serialization.proto.IrStatement statement = 1;</code>
     */
    public IrStatementOrBuilder getStatementOrBuilder(
            int index) {
        return statement_.get(index);
    }

    /**
     * <code>optional int32 origin_name = 2;</code>
     */
    @Override
    public boolean hasOriginName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
    }

    /**
     * <code>optional int32 origin_name = 2;</code>
     */
    @Override
    public int getOriginName() {
        return originName_;
    }

    private void initFields() {
        statement_ = Collections.emptyList();
        originName_ = 0;
    }

    @Override
    public boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        for (int i = 0; i < getStatementCount(); i++) {
            if (!getStatement(i).isInitialized()) {
                memoizedIsInitialized = 0;
                return false;
            }
        }
        memoizedIsInitialized = 1;
        return true;
    }

    @Override
    public void writeTo(CodedOutputStream output)
            throws IOException {
        getSerializedSize();
        for (int i = 0; i < statement_.size(); i++) {
            output.writeMessage(1, statement_.get(i));
        }
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
            output.writeInt32(2, originName_);
        }
        output.writeRawBytes(unknownFields);
    }

    @Override
    public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        for (int i = 0; i < statement_.size(); i++) {
            size += CodedOutputStream
                    .computeMessageSize(1, statement_.get(i));
        }
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
            size += CodedOutputStream
                    .computeInt32Size(2, originName_);
        }
        size += unknownFields.size();
        memoizedSerializedSize = size;
        return size;
    }

    @Override
    protected Object writeReplace()
            throws ObjectStreamException {
        return super.writeReplace();
    }

    @Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    @Override
    public Builder toBuilder() {
        return newBuilder(this);
    }

    /**
     * Protobuf type {@code org.jetbrains.kotlin.backend.common.serialization.proto.IrBlock}
     */
    public static final class Builder extends
            GeneratedMessageLite.Builder<
                    IrBlock, Builder>
            implements
            // @@protoc_insertion_point(builder_implements:org.jetbrains.kotlin.backend.common.serialization.proto.IrBlock)
            IrBlockOrBuilder {
        private int bitField0_;
        private List<IrStatement> statement_ =
                Collections.emptyList();
        private int originName_;

        // Construct using org.jetbrains.kotlin.backend.common.serialization.proto.IrBlock.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private static Builder create() {
            return new Builder();
        }

        private void maybeForceBuilderInitialization() {
        }

        @Override
        public Builder clear() {
            super.clear();
            statement_ = Collections.emptyList();
            bitField0_ &= ~0x00000001;
            originName_ = 0;
            bitField0_ &= ~0x00000002;
            return this;
        }

        @Override
        public Builder clone() {
            return create().mergeFrom(buildPartial());
        }

        @Override
        public IrBlock getDefaultInstanceForType() {
            return getDefaultInstance();
        }

        @Override
        public IrBlock build() {
            IrBlock result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @Override
        public IrBlock buildPartial() {
            IrBlock result = new IrBlock(this);
            int from_bitField0_ = bitField0_;
            int to_bitField0_ = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                statement_ = Collections.unmodifiableList(statement_);
                bitField0_ &= ~0x00000001;
            }
            result.statement_ = statement_;
            if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                to_bitField0_ |= 0x00000001;
            }
            result.originName_ = originName_;
            result.bitField0_ = to_bitField0_;
            return result;
        }

        @Override
        public Builder mergeFrom(IrBlock other) {
            if (other == getDefaultInstance())
                return this;
            if (!other.statement_.isEmpty()) {
                if (statement_.isEmpty()) {
                    statement_ = other.statement_;
                    bitField0_ &= ~0x00000001;
                } else {
                    ensureStatementIsMutable();
                    statement_.addAll(other.statement_);
                }

            }
            if (other.hasOriginName()) {
                setOriginName(other.getOriginName());
            }
            setUnknownFields(
                    getUnknownFields().concat(other.unknownFields));
            return this;
        }

        @Override
        public boolean isInitialized() {
            for (int i = 0; i < getStatementCount(); i++) {
                if (!getStatement(i).isInitialized()) {

                    return false;
                }
            }
            return true;
        }

        @Override
        public Builder mergeFrom(
                CodedInputStream input,
                ExtensionRegistryLite extensionRegistry)
                throws IOException {
            IrBlock parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (InvalidProtocolBufferException e) {
                parsedMessage = (IrBlock) e.getUnfinishedMessage();
                throw e;
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        private void ensureStatementIsMutable() {
            if (!((bitField0_ & 0x00000001) == 0x00000001)) {
                statement_ = new ArrayList<IrStatement>(statement_);
                bitField0_ |= 0x00000001;
            }
        }

        /**
         * <code>repeated .org.jetbrains.kotlin.backend.common.serialization.proto.IrStatement statement = 1;</code>
         */
        @Override
        public List<IrStatement> getStatementList() {
            return Collections.unmodifiableList(statement_);
        }

        /**
         * <code>repeated .org.jetbrains.kotlin.backend.common.serialization.proto.IrStatement statement = 1;</code>
         */
        @Override
        public int getStatementCount() {
            return statement_.size();
        }

        /**
         * <code>repeated .org.jetbrains.kotlin.backend.common.serialization.proto.IrStatement statement = 1;</code>
         */
        @Override
        public IrStatement getStatement(int index) {
            return statement_.get(index);
        }

        /**
         * <code>repeated .org.jetbrains.kotlin.backend.common.serialization.proto.IrStatement statement = 1;</code>
         */
        public Builder setStatement(
                int index, IrStatement value) {
            if (value == null) {
                throw new NullPointerException();
            }
            ensureStatementIsMutable();
            statement_.set(index, value);

            return this;
        }

        /**
         * <code>repeated .org.jetbrains.kotlin.backend.common.serialization.proto.IrStatement statement = 1;</code>
         */
        public Builder setStatement(
                int index, IrStatement.Builder builderForValue) {
            ensureStatementIsMutable();
            statement_.set(index, builderForValue.build());

            return this;
        }

        /**
         * <code>repeated .org.jetbrains.kotlin.backend.common.serialization.proto.IrStatement statement = 1;</code>
         */
        public Builder addStatement(IrStatement value) {
            if (value == null) {
                throw new NullPointerException();
            }
            ensureStatementIsMutable();
            statement_.add(value);

            return this;
        }

        /**
         * <code>repeated .org.jetbrains.kotlin.backend.common.serialization.proto.IrStatement statement = 1;</code>
         */
        public Builder addStatement(
                int index, IrStatement value) {
            if (value == null) {
                throw new NullPointerException();
            }
            ensureStatementIsMutable();
            statement_.add(index, value);

            return this;
        }

        /**
         * <code>repeated .org.jetbrains.kotlin.backend.common.serialization.proto.IrStatement statement = 1;</code>
         */
        public Builder addStatement(
                IrStatement.Builder builderForValue) {
            ensureStatementIsMutable();
            statement_.add(builderForValue.build());

            return this;
        }

        /**
         * <code>repeated .org.jetbrains.kotlin.backend.common.serialization.proto.IrStatement statement = 1;</code>
         */
        public Builder addStatement(
                int index, IrStatement.Builder builderForValue) {
            ensureStatementIsMutable();
            statement_.add(index, builderForValue.build());

            return this;
        }

        /**
         * <code>repeated .org.jetbrains.kotlin.backend.common.serialization.proto.IrStatement statement = 1;</code>
         */
        public Builder addAllStatement(
                Iterable<? extends IrStatement> values) {
            ensureStatementIsMutable();
            addAll(
                    values, statement_);

            return this;
        }

        /**
         * <code>repeated .org.jetbrains.kotlin.backend.common.serialization.proto.IrStatement statement = 1;</code>
         */
        public Builder clearStatement() {
            statement_ = Collections.emptyList();
            bitField0_ &= ~0x00000001;

            return this;
        }

        /**
         * <code>repeated .org.jetbrains.kotlin.backend.common.serialization.proto.IrStatement statement = 1;</code>
         */
        public Builder removeStatement(int index) {
            ensureStatementIsMutable();
            statement_.remove(index);

            return this;
        }

        /**
         * <code>optional int32 origin_name = 2;</code>
         */
        @Override
        public boolean hasOriginName() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        /**
         * <code>optional int32 origin_name = 2;</code>
         */
        @Override
        public int getOriginName() {
            return originName_;
        }

        /**
         * <code>optional int32 origin_name = 2;</code>
         */
        public Builder setOriginName(int value) {
            bitField0_ |= 0x00000002;
            originName_ = value;

            return this;
        }

        /**
         * <code>optional int32 origin_name = 2;</code>
         */
        public Builder clearOriginName() {
            bitField0_ &= ~0x00000002;
            originName_ = 0;

            return this;
        }

        // @@protoc_insertion_point(builder_scope:org.jetbrains.kotlin.backend.common.serialization.proto.IrBlock)
    }

    // @@protoc_insertion_point(class_scope:org.jetbrains.kotlin.backend.common.serialization.proto.IrBlock)
}
