// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compiler/ir/serialization.common/src/KotlinIr.proto

package org.jetbrains.kotlin.backend.common.serialization.proto;

import org.jetbrains.kotlin.protobuf.AbstractParser;
import org.jetbrains.kotlin.protobuf.ByteString;
import org.jetbrains.kotlin.protobuf.CodedInputStream;
import org.jetbrains.kotlin.protobuf.CodedOutputStream;
import org.jetbrains.kotlin.protobuf.ExtensionRegistryLite;
import org.jetbrains.kotlin.protobuf.GeneratedMessageLite;
import org.jetbrains.kotlin.protobuf.InvalidProtocolBufferException;
import org.jetbrains.kotlin.protobuf.Parser;

import java.io.IOException;
import java.io.InputStream;
import java.io.ObjectStreamException;

/**
 * Protobuf type {@code org.jetbrains.kotlin.backend.common.serialization.proto.IrCatch}
 */
public final class IrCatch extends
        GeneratedMessageLite implements
        // @@protoc_insertion_point(message_implements:org.jetbrains.kotlin.backend.common.serialization.proto.IrCatch)
        IrCatchOrBuilder {
    public static final int CATCH_PARAMETER_FIELD_NUMBER = 1;
    public static final int RESULT_FIELD_NUMBER = 2;
    private static final IrCatch defaultInstance;
    private static final long serialVersionUID = 0L;
    public static Parser<IrCatch> PARSER =
            new AbstractParser<IrCatch>() {
                @Override
                public IrCatch parsePartialFrom(
                        CodedInputStream input,
                        ExtensionRegistryLite extensionRegistry)
                        throws InvalidProtocolBufferException {
                    return new IrCatch(input, extensionRegistry);
                }
            };

    static {
        defaultInstance = new IrCatch(true);
        defaultInstance.initFields();
    }

    private final ByteString unknownFields;
    private int bitField0_;
    private IrVariable catchParameter_;
    private IrExpression result_;
    private byte memoizedIsInitialized = -1;
    private int memoizedSerializedSize = -1;

    // Use IrCatch.newBuilder() to construct.
    private IrCatch(GeneratedMessageLite.Builder builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
    }

    private IrCatch(boolean noInit) {
        this.unknownFields = ByteString.EMPTY;
    }

    private IrCatch(
            CodedInputStream input,
            ExtensionRegistryLite extensionRegistry)
            throws InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        ByteString.Output unknownFieldsOutput =
                ByteString.newOutput();
        CodedOutputStream unknownFieldsCodedOutput =
                CodedOutputStream.newInstance(
                        unknownFieldsOutput, 1);
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    default: {
                        if (!parseUnknownField(input, unknownFieldsCodedOutput,
                                extensionRegistry, tag)) {
                            done = true;
                        }
                        break;
                    }
                    case 10: {
                        IrVariable.Builder subBuilder = null;
                        if (((bitField0_ & 0x00000001) == 0x00000001)) {
                            subBuilder = catchParameter_.toBuilder();
                        }
                        catchParameter_ = input.readMessage(IrVariable.PARSER, extensionRegistry);
                        if (subBuilder != null) {
                            subBuilder.mergeFrom(catchParameter_);
                            catchParameter_ = subBuilder.buildPartial();
                        }
                        bitField0_ |= 0x00000001;
                        break;
                    }
                    case 18: {
                        IrExpression.Builder subBuilder = null;
                        if (((bitField0_ & 0x00000002) == 0x00000002)) {
                            subBuilder = result_.toBuilder();
                        }
                        result_ = input.readMessage(IrExpression.PARSER, extensionRegistry);
                        if (subBuilder != null) {
                            subBuilder.mergeFrom(result_);
                            result_ = subBuilder.buildPartial();
                        }
                        bitField0_ |= 0x00000002;
                        break;
                    }
                }
            }
        } catch (InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (IOException e) {
            throw new InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this);
        } finally {
            try {
                unknownFieldsCodedOutput.flush();
            } catch (IOException e) {
                // Should not happen
            } finally {
                unknownFields = unknownFieldsOutput.toByteString();
            }
            makeExtensionsImmutable();
        }
    }

    public static IrCatch getDefaultInstance() {
        return defaultInstance;
    }

    public static IrCatch parseFrom(
            ByteString data)
            throws InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static IrCatch parseFrom(
            ByteString data,
            ExtensionRegistryLite extensionRegistry)
            throws InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static IrCatch parseFrom(byte[] data)
            throws InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static IrCatch parseFrom(
            byte[] data,
            ExtensionRegistryLite extensionRegistry)
            throws InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static IrCatch parseFrom(InputStream input)
            throws IOException {
        return PARSER.parseFrom(input);
    }

    public static IrCatch parseFrom(
            InputStream input,
            ExtensionRegistryLite extensionRegistry)
            throws IOException {
        return PARSER.parseFrom(input, extensionRegistry);
    }

    public static IrCatch parseDelimitedFrom(InputStream input)
            throws IOException {
        return PARSER.parseDelimitedFrom(input);
    }

    public static IrCatch parseDelimitedFrom(
            InputStream input,
            ExtensionRegistryLite extensionRegistry)
            throws IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }

    public static IrCatch parseFrom(
            CodedInputStream input)
            throws IOException {
        return PARSER.parseFrom(input);
    }

    public static IrCatch parseFrom(
            CodedInputStream input,
            ExtensionRegistryLite extensionRegistry)
            throws IOException {
        return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() {
        return Builder.create();
    }

    public static Builder newBuilder(IrCatch prototype) {
        return newBuilder().mergeFrom(prototype);
    }

    @Override
    public IrCatch getDefaultInstanceForType() {
        return defaultInstance;
    }

    @Override
    public Parser<IrCatch> getParserForType() {
        return PARSER;
    }

    /**
     * <code>required .org.jetbrains.kotlin.backend.common.serialization.proto.IrVariable catch_parameter = 1;</code>
     */
    @Override
    public boolean hasCatchParameter() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
    }

    /**
     * <code>required .org.jetbrains.kotlin.backend.common.serialization.proto.IrVariable catch_parameter = 1;</code>
     */
    @Override
    public IrVariable getCatchParameter() {
        return catchParameter_;
    }

    /**
     * <code>required .org.jetbrains.kotlin.backend.common.serialization.proto.IrExpression result = 2;</code>
     */
    @Override
    public boolean hasResult() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
    }

    /**
     * <code>required .org.jetbrains.kotlin.backend.common.serialization.proto.IrExpression result = 2;</code>
     */
    @Override
    public IrExpression getResult() {
        return result_;
    }

    private void initFields() {
        catchParameter_ = IrVariable.getDefaultInstance();
        result_ = IrExpression.getDefaultInstance();
    }

    @Override
    public boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasCatchParameter()) {
            memoizedIsInitialized = 0;
            return false;
        }
        if (!hasResult()) {
            memoizedIsInitialized = 0;
            return false;
        }
        if (!getCatchParameter().isInitialized()) {
            memoizedIsInitialized = 0;
            return false;
        }
        if (!getResult().isInitialized()) {
            memoizedIsInitialized = 0;
            return false;
        }
        memoizedIsInitialized = 1;
        return true;
    }

    @Override
    public void writeTo(CodedOutputStream output)
            throws IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
            output.writeMessage(1, catchParameter_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
            output.writeMessage(2, result_);
        }
        output.writeRawBytes(unknownFields);
    }

    @Override
    public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
            size += CodedOutputStream
                    .computeMessageSize(1, catchParameter_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
            size += CodedOutputStream
                    .computeMessageSize(2, result_);
        }
        size += unknownFields.size();
        memoizedSerializedSize = size;
        return size;
    }

    @Override
    protected Object writeReplace()
            throws ObjectStreamException {
        return super.writeReplace();
    }

    @Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    @Override
    public Builder toBuilder() {
        return newBuilder(this);
    }

    /**
     * Protobuf type {@code org.jetbrains.kotlin.backend.common.serialization.proto.IrCatch}
     */
    public static final class Builder extends
            GeneratedMessageLite.Builder<
                    IrCatch, Builder>
            implements
            // @@protoc_insertion_point(builder_implements:org.jetbrains.kotlin.backend.common.serialization.proto.IrCatch)
            IrCatchOrBuilder {
        private int bitField0_;
        private IrVariable catchParameter_ = IrVariable.getDefaultInstance();
        private IrExpression result_ = IrExpression.getDefaultInstance();

        // Construct using org.jetbrains.kotlin.backend.common.serialization.proto.IrCatch.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private static Builder create() {
            return new Builder();
        }

        private void maybeForceBuilderInitialization() {
        }

        @Override
        public Builder clear() {
            super.clear();
            catchParameter_ = IrVariable.getDefaultInstance();
            bitField0_ &= ~0x00000001;
            result_ = IrExpression.getDefaultInstance();
            bitField0_ &= ~0x00000002;
            return this;
        }

        @Override
        public Builder clone() {
            return create().mergeFrom(buildPartial());
        }

        @Override
        public IrCatch getDefaultInstanceForType() {
            return getDefaultInstance();
        }

        @Override
        public IrCatch build() {
            IrCatch result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @Override
        public IrCatch buildPartial() {
            IrCatch result = new IrCatch(this);
            int from_bitField0_ = bitField0_;
            int to_bitField0_ = 0;
            if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                to_bitField0_ |= 0x00000001;
            }
            result.catchParameter_ = catchParameter_;
            if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                to_bitField0_ |= 0x00000002;
            }
            result.result_ = result_;
            result.bitField0_ = to_bitField0_;
            return result;
        }

        @Override
        public Builder mergeFrom(IrCatch other) {
            if (other == getDefaultInstance())
                return this;
            if (other.hasCatchParameter()) {
                mergeCatchParameter(other.getCatchParameter());
            }
            if (other.hasResult()) {
                mergeResult(other.getResult());
            }
            setUnknownFields(
                    getUnknownFields().concat(other.unknownFields));
            return this;
        }

        @Override
        public boolean isInitialized() {
            if (!hasCatchParameter()) {

                return false;
            }
            if (!hasResult()) {

                return false;
            }
            if (!getCatchParameter().isInitialized()) {

                return false;
            }
            if (!getResult().isInitialized()) {

                return false;
            }
            return true;
        }

        @Override
        public Builder mergeFrom(
                CodedInputStream input,
                ExtensionRegistryLite extensionRegistry)
                throws IOException {
            IrCatch parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (InvalidProtocolBufferException e) {
                parsedMessage = (IrCatch) e.getUnfinishedMessage();
                throw e;
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        /**
         * <code>required .org.jetbrains.kotlin.backend.common.serialization.proto.IrVariable catch_parameter = 1;</code>
         */
        @Override
        public boolean hasCatchParameter() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <code>required .org.jetbrains.kotlin.backend.common.serialization.proto.IrVariable catch_parameter = 1;</code>
         */
        @Override
        public IrVariable getCatchParameter() {
            return catchParameter_;
        }

        /**
         * <code>required .org.jetbrains.kotlin.backend.common.serialization.proto.IrVariable catch_parameter = 1;</code>
         */
        public Builder setCatchParameter(IrVariable value) {
            if (value == null) {
                throw new NullPointerException();
            }
            catchParameter_ = value;

            bitField0_ |= 0x00000001;
            return this;
        }

        /**
         * <code>required .org.jetbrains.kotlin.backend.common.serialization.proto.IrVariable catch_parameter = 1;</code>
         */
        public Builder setCatchParameter(
                IrVariable.Builder builderForValue) {
            catchParameter_ = builderForValue.build();

            bitField0_ |= 0x00000001;
            return this;
        }

        /**
         * <code>required .org.jetbrains.kotlin.backend.common.serialization.proto.IrVariable catch_parameter = 1;</code>
         */
        public Builder mergeCatchParameter(IrVariable value) {
            if (((bitField0_ & 0x00000001) == 0x00000001) &&
                    catchParameter_ != IrVariable.getDefaultInstance()) {
                catchParameter_ =
                        IrVariable.newBuilder(catchParameter_).mergeFrom(value).buildPartial();
            } else {
                catchParameter_ = value;
            }

            bitField0_ |= 0x00000001;
            return this;
        }

        /**
         * <code>required .org.jetbrains.kotlin.backend.common.serialization.proto.IrVariable catch_parameter = 1;</code>
         */
        public Builder clearCatchParameter() {
            catchParameter_ = IrVariable.getDefaultInstance();

            bitField0_ &= ~0x00000001;
            return this;
        }

        /**
         * <code>required .org.jetbrains.kotlin.backend.common.serialization.proto.IrExpression result = 2;</code>
         */
        @Override
        public boolean hasResult() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        /**
         * <code>required .org.jetbrains.kotlin.backend.common.serialization.proto.IrExpression result = 2;</code>
         */
        @Override
        public IrExpression getResult() {
            return result_;
        }

        /**
         * <code>required .org.jetbrains.kotlin.backend.common.serialization.proto.IrExpression result = 2;</code>
         */
        public Builder setResult(IrExpression value) {
            if (value == null) {
                throw new NullPointerException();
            }
            result_ = value;

            bitField0_ |= 0x00000002;
            return this;
        }

        /**
         * <code>required .org.jetbrains.kotlin.backend.common.serialization.proto.IrExpression result = 2;</code>
         */
        public Builder setResult(
                IrExpression.Builder builderForValue) {
            result_ = builderForValue.build();

            bitField0_ |= 0x00000002;
            return this;
        }

        /**
         * <code>required .org.jetbrains.kotlin.backend.common.serialization.proto.IrExpression result = 2;</code>
         */
        public Builder mergeResult(IrExpression value) {
            if (((bitField0_ & 0x00000002) == 0x00000002) &&
                    result_ != IrExpression.getDefaultInstance()) {
                result_ =
                        IrExpression.newBuilder(result_).mergeFrom(value).buildPartial();
            } else {
                result_ = value;
            }

            bitField0_ |= 0x00000002;
            return this;
        }

        /**
         * <code>required .org.jetbrains.kotlin.backend.common.serialization.proto.IrExpression result = 2;</code>
         */
        public Builder clearResult() {
            result_ = IrExpression.getDefaultInstance();

            bitField0_ &= ~0x00000002;
            return this;
        }

        // @@protoc_insertion_point(builder_scope:org.jetbrains.kotlin.backend.common.serialization.proto.IrCatch)
    }

    // @@protoc_insertion_point(class_scope:org.jetbrains.kotlin.backend.common.serialization.proto.IrCatch)
}
