// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compiler/ir/serialization.common/src/KotlinIr.proto

package org.jetbrains.kotlin.backend.common.serialization.proto;

import org.jetbrains.kotlin.protobuf.AbstractParser;
import org.jetbrains.kotlin.protobuf.ByteString;
import org.jetbrains.kotlin.protobuf.CodedInputStream;
import org.jetbrains.kotlin.protobuf.CodedOutputStream;
import org.jetbrains.kotlin.protobuf.ExtensionRegistryLite;
import org.jetbrains.kotlin.protobuf.GeneratedMessageLite;
import org.jetbrains.kotlin.protobuf.InvalidProtocolBufferException;
import org.jetbrains.kotlin.protobuf.Parser;

import java.io.IOException;
import java.io.InputStream;
import java.io.ObjectStreamException;

/**
 * Protobuf type {@code org.jetbrains.kotlin.backend.common.serialization.proto.IrClassReference}
 */
public final class IrClassReference extends
        GeneratedMessageLite implements
        // @@protoc_insertion_point(message_implements:org.jetbrains.kotlin.backend.common.serialization.proto.IrClassReference)
        IrClassReferenceOrBuilder {
    public static final int CLASS_SYMBOL_FIELD_NUMBER = 1;
    public static final int CLASS_TYPE_FIELD_NUMBER = 2;
    private static final IrClassReference defaultInstance;
    private static final long serialVersionUID = 0L;
    public static Parser<IrClassReference> PARSER =
            new AbstractParser<IrClassReference>() {
                @Override
                public IrClassReference parsePartialFrom(
                        CodedInputStream input,
                        ExtensionRegistryLite extensionRegistry)
                        throws InvalidProtocolBufferException {
                    return new IrClassReference(input, extensionRegistry);
                }
            };

    static {
        defaultInstance = new IrClassReference(true);
        defaultInstance.initFields();
    }

    private final ByteString unknownFields;
    private int bitField0_;
    private long classSymbol_;
    private int classType_;
    private byte memoizedIsInitialized = -1;
    private int memoizedSerializedSize = -1;

    // Use IrClassReference.newBuilder() to construct.
    private IrClassReference(GeneratedMessageLite.Builder builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
    }

    private IrClassReference(boolean noInit) {
        this.unknownFields = ByteString.EMPTY;
    }

    private IrClassReference(
            CodedInputStream input,
            ExtensionRegistryLite extensionRegistry)
            throws InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        ByteString.Output unknownFieldsOutput =
                ByteString.newOutput();
        CodedOutputStream unknownFieldsCodedOutput =
                CodedOutputStream.newInstance(
                        unknownFieldsOutput, 1);
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    default: {
                        if (!parseUnknownField(input, unknownFieldsCodedOutput,
                                extensionRegistry, tag)) {
                            done = true;
                        }
                        break;
                    }
                    case 8: {
                        bitField0_ |= 0x00000001;
                        classSymbol_ = input.readInt64();
                        break;
                    }
                    case 16: {
                        bitField0_ |= 0x00000002;
                        classType_ = input.readInt32();
                        break;
                    }
                }
            }
        } catch (InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (IOException e) {
            throw new InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this);
        } finally {
            try {
                unknownFieldsCodedOutput.flush();
            } catch (IOException e) {
                // Should not happen
            } finally {
                unknownFields = unknownFieldsOutput.toByteString();
            }
            makeExtensionsImmutable();
        }
    }

    public static IrClassReference getDefaultInstance() {
        return defaultInstance;
    }

    public static IrClassReference parseFrom(
            ByteString data)
            throws InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static IrClassReference parseFrom(
            ByteString data,
            ExtensionRegistryLite extensionRegistry)
            throws InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static IrClassReference parseFrom(byte[] data)
            throws InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static IrClassReference parseFrom(
            byte[] data,
            ExtensionRegistryLite extensionRegistry)
            throws InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static IrClassReference parseFrom(InputStream input)
            throws IOException {
        return PARSER.parseFrom(input);
    }

    public static IrClassReference parseFrom(
            InputStream input,
            ExtensionRegistryLite extensionRegistry)
            throws IOException {
        return PARSER.parseFrom(input, extensionRegistry);
    }

    public static IrClassReference parseDelimitedFrom(InputStream input)
            throws IOException {
        return PARSER.parseDelimitedFrom(input);
    }

    public static IrClassReference parseDelimitedFrom(
            InputStream input,
            ExtensionRegistryLite extensionRegistry)
            throws IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }

    public static IrClassReference parseFrom(
            CodedInputStream input)
            throws IOException {
        return PARSER.parseFrom(input);
    }

    public static IrClassReference parseFrom(
            CodedInputStream input,
            ExtensionRegistryLite extensionRegistry)
            throws IOException {
        return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() {
        return Builder.create();
    }

    public static Builder newBuilder(IrClassReference prototype) {
        return newBuilder().mergeFrom(prototype);
    }

    @Override
    public IrClassReference getDefaultInstanceForType() {
        return defaultInstance;
    }

    @Override
    public Parser<IrClassReference> getParserForType() {
        return PARSER;
    }

    /**
     * <code>required int64 class_symbol = 1;</code>
     */
    @Override
    public boolean hasClassSymbol() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
    }

    /**
     * <code>required int64 class_symbol = 1;</code>
     */
    @Override
    public long getClassSymbol() {
        return classSymbol_;
    }

    /**
     * <code>required int32 class_type = 2;</code>
     */
    @Override
    public boolean hasClassType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
    }

    /**
     * <code>required int32 class_type = 2;</code>
     */
    @Override
    public int getClassType() {
        return classType_;
    }

    private void initFields() {
        classSymbol_ = 0L;
        classType_ = 0;
    }

    @Override
    public boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasClassSymbol()) {
            memoizedIsInitialized = 0;
            return false;
        }
        if (!hasClassType()) {
            memoizedIsInitialized = 0;
            return false;
        }
        memoizedIsInitialized = 1;
        return true;
    }

    @Override
    public void writeTo(CodedOutputStream output)
            throws IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
            output.writeInt64(1, classSymbol_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
            output.writeInt32(2, classType_);
        }
        output.writeRawBytes(unknownFields);
    }

    @Override
    public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
            size += CodedOutputStream
                    .computeInt64Size(1, classSymbol_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
            size += CodedOutputStream
                    .computeInt32Size(2, classType_);
        }
        size += unknownFields.size();
        memoizedSerializedSize = size;
        return size;
    }

    @Override
    protected Object writeReplace()
            throws ObjectStreamException {
        return super.writeReplace();
    }

    @Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    @Override
    public Builder toBuilder() {
        return newBuilder(this);
    }

    /**
     * Protobuf type {@code org.jetbrains.kotlin.backend.common.serialization.proto.IrClassReference}
     */
    public static final class Builder extends
            GeneratedMessageLite.Builder<
                    IrClassReference, Builder>
            implements
            // @@protoc_insertion_point(builder_implements:org.jetbrains.kotlin.backend.common.serialization.proto.IrClassReference)
            IrClassReferenceOrBuilder {
        private int bitField0_;
        private long classSymbol_;
        private int classType_;

        // Construct using org.jetbrains.kotlin.backend.common.serialization.proto.IrClassReference.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private static Builder create() {
            return new Builder();
        }

        private void maybeForceBuilderInitialization() {
        }

        @Override
        public Builder clear() {
            super.clear();
            classSymbol_ = 0L;
            bitField0_ &= ~0x00000001;
            classType_ = 0;
            bitField0_ &= ~0x00000002;
            return this;
        }

        @Override
        public Builder clone() {
            return create().mergeFrom(buildPartial());
        }

        @Override
        public IrClassReference getDefaultInstanceForType() {
            return getDefaultInstance();
        }

        @Override
        public IrClassReference build() {
            IrClassReference result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @Override
        public IrClassReference buildPartial() {
            IrClassReference result = new IrClassReference(this);
            int from_bitField0_ = bitField0_;
            int to_bitField0_ = 0;
            if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                to_bitField0_ |= 0x00000001;
            }
            result.classSymbol_ = classSymbol_;
            if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                to_bitField0_ |= 0x00000002;
            }
            result.classType_ = classType_;
            result.bitField0_ = to_bitField0_;
            return result;
        }

        @Override
        public Builder mergeFrom(IrClassReference other) {
            if (other == getDefaultInstance())
                return this;
            if (other.hasClassSymbol()) {
                setClassSymbol(other.getClassSymbol());
            }
            if (other.hasClassType()) {
                setClassType(other.getClassType());
            }
            setUnknownFields(
                    getUnknownFields().concat(other.unknownFields));
            return this;
        }

        @Override
        public boolean isInitialized() {
            if (!hasClassSymbol()) {

                return false;
            }
            if (!hasClassType()) {

                return false;
            }
            return true;
        }

        @Override
        public Builder mergeFrom(
                CodedInputStream input,
                ExtensionRegistryLite extensionRegistry)
                throws IOException {
            IrClassReference parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (InvalidProtocolBufferException e) {
                parsedMessage = (IrClassReference) e.getUnfinishedMessage();
                throw e;
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        /**
         * <code>required int64 class_symbol = 1;</code>
         */
        @Override
        public boolean hasClassSymbol() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <code>required int64 class_symbol = 1;</code>
         */
        @Override
        public long getClassSymbol() {
            return classSymbol_;
        }

        /**
         * <code>required int64 class_symbol = 1;</code>
         */
        public Builder setClassSymbol(long value) {
            bitField0_ |= 0x00000001;
            classSymbol_ = value;

            return this;
        }

        /**
         * <code>required int64 class_symbol = 1;</code>
         */
        public Builder clearClassSymbol() {
            bitField0_ &= ~0x00000001;
            classSymbol_ = 0L;

            return this;
        }

        /**
         * <code>required int32 class_type = 2;</code>
         */
        @Override
        public boolean hasClassType() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        /**
         * <code>required int32 class_type = 2;</code>
         */
        @Override
        public int getClassType() {
            return classType_;
        }

        /**
         * <code>required int32 class_type = 2;</code>
         */
        public Builder setClassType(int value) {
            bitField0_ |= 0x00000002;
            classType_ = value;

            return this;
        }

        /**
         * <code>required int32 class_type = 2;</code>
         */
        public Builder clearClassType() {
            bitField0_ &= ~0x00000002;
            classType_ = 0;

            return this;
        }

        // @@protoc_insertion_point(builder_scope:org.jetbrains.kotlin.backend.common.serialization.proto.IrClassReference)
    }

    // @@protoc_insertion_point(class_scope:org.jetbrains.kotlin.backend.common.serialization.proto.IrClassReference)
}
