// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compiler/ir/serialization.common/src/KotlinIr.proto

package org.jetbrains.kotlin.backend.common.serialization.proto;

import org.jetbrains.kotlin.protobuf.AbstractParser;
import org.jetbrains.kotlin.protobuf.ByteString;
import org.jetbrains.kotlin.protobuf.CodedInputStream;
import org.jetbrains.kotlin.protobuf.CodedOutputStream;
import org.jetbrains.kotlin.protobuf.ExtensionRegistryLite;
import org.jetbrains.kotlin.protobuf.GeneratedMessageLite;
import org.jetbrains.kotlin.protobuf.InvalidProtocolBufferException;
import org.jetbrains.kotlin.protobuf.Parser;

import java.io.IOException;
import java.io.InputStream;
import java.io.ObjectStreamException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/**
 * Protobuf type {@code org.jetbrains.kotlin.backend.common.serialization.proto.IrErrorCallExpression}
 */
public final class IrErrorCallExpression extends
        GeneratedMessageLite implements
        // @@protoc_insertion_point(message_implements:org.jetbrains.kotlin.backend.common.serialization.proto.IrErrorCallExpression)
        IrErrorCallExpressionOrBuilder {
    public static final int DESCRIPTION_FIELD_NUMBER = 1;
    public static final int RECEIVER_FIELD_NUMBER = 2;
    public static final int VALUE_ARGUMENT_FIELD_NUMBER = 3;
    private static final IrErrorCallExpression defaultInstance;
    private static final long serialVersionUID = 0L;
    public static Parser<IrErrorCallExpression> PARSER =
            new AbstractParser<IrErrorCallExpression>() {
                @Override
                public IrErrorCallExpression parsePartialFrom(
                        CodedInputStream input,
                        ExtensionRegistryLite extensionRegistry)
                        throws InvalidProtocolBufferException {
                    return new IrErrorCallExpression(input, extensionRegistry);
                }
            };

    static {
        defaultInstance = new IrErrorCallExpression(true);
        defaultInstance.initFields();
    }

    private final ByteString unknownFields;
    private int bitField0_;
    private int description_;
    private IrExpression receiver_;
    private List<IrExpression> valueArgument_;
    private byte memoizedIsInitialized = -1;
    private int memoizedSerializedSize = -1;

    // Use IrErrorCallExpression.newBuilder() to construct.
    private IrErrorCallExpression(GeneratedMessageLite.Builder builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
    }
    private IrErrorCallExpression(boolean noInit) {
        this.unknownFields = ByteString.EMPTY;
    }

    private IrErrorCallExpression(
            CodedInputStream input,
            ExtensionRegistryLite extensionRegistry)
            throws InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        ByteString.Output unknownFieldsOutput =
                ByteString.newOutput();
        CodedOutputStream unknownFieldsCodedOutput =
                CodedOutputStream.newInstance(
                        unknownFieldsOutput, 1);
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    default: {
                        if (!parseUnknownField(input, unknownFieldsCodedOutput,
                                extensionRegistry, tag)) {
                            done = true;
                        }
                        break;
                    }
                    case 8: {
                        bitField0_ |= 0x00000001;
                        description_ = input.readInt32();
                        break;
                    }
                    case 18: {
                        IrExpression.Builder subBuilder = null;
                        if (((bitField0_ & 0x00000002) == 0x00000002)) {
                            subBuilder = receiver_.toBuilder();
                        }
                        receiver_ = input.readMessage(IrExpression.PARSER, extensionRegistry);
                        if (subBuilder != null) {
                            subBuilder.mergeFrom(receiver_);
                            receiver_ = subBuilder.buildPartial();
                        }
                        bitField0_ |= 0x00000002;
                        break;
                    }
                    case 26: {
                        if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                            valueArgument_ = new ArrayList<IrExpression>();
                            mutable_bitField0_ |= 0x00000004;
                        }
                        valueArgument_.add(input.readMessage(IrExpression.PARSER, extensionRegistry));
                        break;
                    }
                }
            }
        } catch (InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (IOException e) {
            throw new InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this);
        } finally {
            if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                valueArgument_ = Collections.unmodifiableList(valueArgument_);
            }
            try {
                unknownFieldsCodedOutput.flush();
            } catch (IOException e) {
                // Should not happen
            } finally {
                unknownFields = unknownFieldsOutput.toByteString();
            }
            makeExtensionsImmutable();
        }
    }

    public static IrErrorCallExpression getDefaultInstance() {
        return defaultInstance;
    }

    public static IrErrorCallExpression parseFrom(
            ByteString data)
            throws InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static IrErrorCallExpression parseFrom(
            ByteString data,
            ExtensionRegistryLite extensionRegistry)
            throws InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static IrErrorCallExpression parseFrom(byte[] data)
            throws InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static IrErrorCallExpression parseFrom(
            byte[] data,
            ExtensionRegistryLite extensionRegistry)
            throws InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static IrErrorCallExpression parseFrom(InputStream input)
            throws IOException {
        return PARSER.parseFrom(input);
    }

    public static IrErrorCallExpression parseFrom(
            InputStream input,
            ExtensionRegistryLite extensionRegistry)
            throws IOException {
        return PARSER.parseFrom(input, extensionRegistry);
    }

    public static IrErrorCallExpression parseDelimitedFrom(InputStream input)
            throws IOException {
        return PARSER.parseDelimitedFrom(input);
    }

    public static IrErrorCallExpression parseDelimitedFrom(
            InputStream input,
            ExtensionRegistryLite extensionRegistry)
            throws IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }

    public static IrErrorCallExpression parseFrom(
            CodedInputStream input)
            throws IOException {
        return PARSER.parseFrom(input);
    }

    public static IrErrorCallExpression parseFrom(
            CodedInputStream input,
            ExtensionRegistryLite extensionRegistry)
            throws IOException {
        return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() {
        return Builder.create();
    }

    public static Builder newBuilder(IrErrorCallExpression prototype) {
        return newBuilder().mergeFrom(prototype);
    }

    @Override
    public IrErrorCallExpression getDefaultInstanceForType() {
        return defaultInstance;
    }

    @Override
    public Parser<IrErrorCallExpression> getParserForType() {
        return PARSER;
    }

    /**
     * <code>required int32 description = 1;</code>
     */
    @Override
    public boolean hasDescription() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
    }

    /**
     * <code>required int32 description = 1;</code>
     */
    @Override
    public int getDescription() {
        return description_;
    }

    /**
     * <code>optional .org.jetbrains.kotlin.backend.common.serialization.proto.IrExpression receiver = 2;</code>
     */
    @Override
    public boolean hasReceiver() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
    }

    /**
     * <code>optional .org.jetbrains.kotlin.backend.common.serialization.proto.IrExpression receiver = 2;</code>
     */
    @Override
    public IrExpression getReceiver() {
        return receiver_;
    }

    /**
     * <code>repeated .org.jetbrains.kotlin.backend.common.serialization.proto.IrExpression value_argument = 3;</code>
     */
    @Override
    public List<IrExpression> getValueArgumentList() {
        return valueArgument_;
    }

    /**
     * <code>repeated .org.jetbrains.kotlin.backend.common.serialization.proto.IrExpression value_argument = 3;</code>
     */
    public List<? extends IrExpressionOrBuilder>
    getValueArgumentOrBuilderList() {
        return valueArgument_;
    }

    /**
     * <code>repeated .org.jetbrains.kotlin.backend.common.serialization.proto.IrExpression value_argument = 3;</code>
     */
    @Override
    public int getValueArgumentCount() {
        return valueArgument_.size();
    }

    /**
     * <code>repeated .org.jetbrains.kotlin.backend.common.serialization.proto.IrExpression value_argument = 3;</code>
     */
    @Override
    public IrExpression getValueArgument(int index) {
        return valueArgument_.get(index);
    }

    /**
     * <code>repeated .org.jetbrains.kotlin.backend.common.serialization.proto.IrExpression value_argument = 3;</code>
     */
    public IrExpressionOrBuilder getValueArgumentOrBuilder(
            int index) {
        return valueArgument_.get(index);
    }

    private void initFields() {
        description_ = 0;
        receiver_ = IrExpression.getDefaultInstance();
        valueArgument_ = Collections.emptyList();
    }

    @Override
    public boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasDescription()) {
            memoizedIsInitialized = 0;
            return false;
        }
        if (hasReceiver()) {
            if (!getReceiver().isInitialized()) {
                memoizedIsInitialized = 0;
                return false;
            }
        }
        for (int i = 0; i < getValueArgumentCount(); i++) {
            if (!getValueArgument(i).isInitialized()) {
                memoizedIsInitialized = 0;
                return false;
            }
        }
        memoizedIsInitialized = 1;
        return true;
    }

    @Override
    public void writeTo(CodedOutputStream output)
            throws IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
            output.writeInt32(1, description_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
            output.writeMessage(2, receiver_);
        }
        for (int i = 0; i < valueArgument_.size(); i++) {
            output.writeMessage(3, valueArgument_.get(i));
        }
        output.writeRawBytes(unknownFields);
    }

    @Override
    public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
            size += CodedOutputStream
                    .computeInt32Size(1, description_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
            size += CodedOutputStream
                    .computeMessageSize(2, receiver_);
        }
        for (int i = 0; i < valueArgument_.size(); i++) {
            size += CodedOutputStream
                    .computeMessageSize(3, valueArgument_.get(i));
        }
        size += unknownFields.size();
        memoizedSerializedSize = size;
        return size;
    }

    @Override
    protected Object writeReplace()
            throws ObjectStreamException {
        return super.writeReplace();
    }

    @Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    @Override
    public Builder toBuilder() {
        return newBuilder(this);
    }

    /**
     * Protobuf type {@code org.jetbrains.kotlin.backend.common.serialization.proto.IrErrorCallExpression}
     */
    public static final class Builder extends
            GeneratedMessageLite.Builder<
                    IrErrorCallExpression, Builder>
            implements
            // @@protoc_insertion_point(builder_implements:org.jetbrains.kotlin.backend.common.serialization.proto.IrErrorCallExpression)
            IrErrorCallExpressionOrBuilder {
        private int bitField0_;
        private int description_;
        private IrExpression receiver_ = IrExpression.getDefaultInstance();
        private List<IrExpression> valueArgument_ =
                Collections.emptyList();

        // Construct using org.jetbrains.kotlin.backend.common.serialization.proto.IrErrorCallExpression.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private static Builder create() {
            return new Builder();
        }

        private void maybeForceBuilderInitialization() {
        }

        @Override
        public Builder clear() {
            super.clear();
            description_ = 0;
            bitField0_ &= ~0x00000001;
            receiver_ = IrExpression.getDefaultInstance();
            bitField0_ &= ~0x00000002;
            valueArgument_ = Collections.emptyList();
            bitField0_ &= ~0x00000004;
            return this;
        }

        @Override
        public Builder clone() {
            return create().mergeFrom(buildPartial());
        }

        @Override
        public IrErrorCallExpression getDefaultInstanceForType() {
            return getDefaultInstance();
        }

        @Override
        public IrErrorCallExpression build() {
            IrErrorCallExpression result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @Override
        public IrErrorCallExpression buildPartial() {
            IrErrorCallExpression result = new IrErrorCallExpression(this);
            int from_bitField0_ = bitField0_;
            int to_bitField0_ = 0;
            if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                to_bitField0_ |= 0x00000001;
            }
            result.description_ = description_;
            if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                to_bitField0_ |= 0x00000002;
            }
            result.receiver_ = receiver_;
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                valueArgument_ = Collections.unmodifiableList(valueArgument_);
                bitField0_ &= ~0x00000004;
            }
            result.valueArgument_ = valueArgument_;
            result.bitField0_ = to_bitField0_;
            return result;
        }

        @Override
        public Builder mergeFrom(IrErrorCallExpression other) {
            if (other == getDefaultInstance())
                return this;
            if (other.hasDescription()) {
                setDescription(other.getDescription());
            }
            if (other.hasReceiver()) {
                mergeReceiver(other.getReceiver());
            }
            if (!other.valueArgument_.isEmpty()) {
                if (valueArgument_.isEmpty()) {
                    valueArgument_ = other.valueArgument_;
                    bitField0_ &= ~0x00000004;
                } else {
                    ensureValueArgumentIsMutable();
                    valueArgument_.addAll(other.valueArgument_);
                }

            }
            setUnknownFields(
                    getUnknownFields().concat(other.unknownFields));
            return this;
        }

        @Override
        public boolean isInitialized() {
            if (!hasDescription()) {

                return false;
            }
            if (hasReceiver()) {
                if (!getReceiver().isInitialized()) {

                    return false;
                }
            }
            for (int i = 0; i < getValueArgumentCount(); i++) {
                if (!getValueArgument(i).isInitialized()) {

                    return false;
                }
            }
            return true;
        }

        @Override
        public Builder mergeFrom(
                CodedInputStream input,
                ExtensionRegistryLite extensionRegistry)
                throws IOException {
            IrErrorCallExpression parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (InvalidProtocolBufferException e) {
                parsedMessage = (IrErrorCallExpression) e.getUnfinishedMessage();
                throw e;
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        /**
         * <code>required int32 description = 1;</code>
         */
        @Override
        public boolean hasDescription() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <code>required int32 description = 1;</code>
         */
        @Override
        public int getDescription() {
            return description_;
        }

        /**
         * <code>required int32 description = 1;</code>
         */
        public Builder setDescription(int value) {
            bitField0_ |= 0x00000001;
            description_ = value;

            return this;
        }

        /**
         * <code>required int32 description = 1;</code>
         */
        public Builder clearDescription() {
            bitField0_ &= ~0x00000001;
            description_ = 0;

            return this;
        }

        /**
         * <code>optional .org.jetbrains.kotlin.backend.common.serialization.proto.IrExpression receiver = 2;</code>
         */
        @Override
        public boolean hasReceiver() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        /**
         * <code>optional .org.jetbrains.kotlin.backend.common.serialization.proto.IrExpression receiver = 2;</code>
         */
        @Override
        public IrExpression getReceiver() {
            return receiver_;
        }

        /**
         * <code>optional .org.jetbrains.kotlin.backend.common.serialization.proto.IrExpression receiver = 2;</code>
         */
        public Builder setReceiver(IrExpression value) {
            if (value == null) {
                throw new NullPointerException();
            }
            receiver_ = value;

            bitField0_ |= 0x00000002;
            return this;
        }

        /**
         * <code>optional .org.jetbrains.kotlin.backend.common.serialization.proto.IrExpression receiver = 2;</code>
         */
        public Builder setReceiver(
                IrExpression.Builder builderForValue) {
            receiver_ = builderForValue.build();

            bitField0_ |= 0x00000002;
            return this;
        }

        /**
         * <code>optional .org.jetbrains.kotlin.backend.common.serialization.proto.IrExpression receiver = 2;</code>
         */
        public Builder mergeReceiver(IrExpression value) {
            if (((bitField0_ & 0x00000002) == 0x00000002) &&
                    receiver_ != IrExpression.getDefaultInstance()) {
                receiver_ =
                        IrExpression.newBuilder(receiver_).mergeFrom(value).buildPartial();
            } else {
                receiver_ = value;
            }

            bitField0_ |= 0x00000002;
            return this;
        }

        /**
         * <code>optional .org.jetbrains.kotlin.backend.common.serialization.proto.IrExpression receiver = 2;</code>
         */
        public Builder clearReceiver() {
            receiver_ = IrExpression.getDefaultInstance();

            bitField0_ &= ~0x00000002;
            return this;
        }

        private void ensureValueArgumentIsMutable() {
            if (!((bitField0_ & 0x00000004) == 0x00000004)) {
                valueArgument_ = new ArrayList<IrExpression>(valueArgument_);
                bitField0_ |= 0x00000004;
            }
        }

        /**
         * <code>repeated .org.jetbrains.kotlin.backend.common.serialization.proto.IrExpression value_argument = 3;</code>
         */
        @Override
        public List<IrExpression> getValueArgumentList() {
            return Collections.unmodifiableList(valueArgument_);
        }

        /**
         * <code>repeated .org.jetbrains.kotlin.backend.common.serialization.proto.IrExpression value_argument = 3;</code>
         */
        @Override
        public int getValueArgumentCount() {
            return valueArgument_.size();
        }

        /**
         * <code>repeated .org.jetbrains.kotlin.backend.common.serialization.proto.IrExpression value_argument = 3;</code>
         */
        @Override
        public IrExpression getValueArgument(int index) {
            return valueArgument_.get(index);
        }

        /**
         * <code>repeated .org.jetbrains.kotlin.backend.common.serialization.proto.IrExpression value_argument = 3;</code>
         */
        public Builder setValueArgument(
                int index, IrExpression value) {
            if (value == null) {
                throw new NullPointerException();
            }
            ensureValueArgumentIsMutable();
            valueArgument_.set(index, value);

            return this;
        }

        /**
         * <code>repeated .org.jetbrains.kotlin.backend.common.serialization.proto.IrExpression value_argument = 3;</code>
         */
        public Builder setValueArgument(
                int index, IrExpression.Builder builderForValue) {
            ensureValueArgumentIsMutable();
            valueArgument_.set(index, builderForValue.build());

            return this;
        }

        /**
         * <code>repeated .org.jetbrains.kotlin.backend.common.serialization.proto.IrExpression value_argument = 3;</code>
         */
        public Builder addValueArgument(IrExpression value) {
            if (value == null) {
                throw new NullPointerException();
            }
            ensureValueArgumentIsMutable();
            valueArgument_.add(value);

            return this;
        }

        /**
         * <code>repeated .org.jetbrains.kotlin.backend.common.serialization.proto.IrExpression value_argument = 3;</code>
         */
        public Builder addValueArgument(
                int index, IrExpression value) {
            if (value == null) {
                throw new NullPointerException();
            }
            ensureValueArgumentIsMutable();
            valueArgument_.add(index, value);

            return this;
        }

        /**
         * <code>repeated .org.jetbrains.kotlin.backend.common.serialization.proto.IrExpression value_argument = 3;</code>
         */
        public Builder addValueArgument(
                IrExpression.Builder builderForValue) {
            ensureValueArgumentIsMutable();
            valueArgument_.add(builderForValue.build());

            return this;
        }

        /**
         * <code>repeated .org.jetbrains.kotlin.backend.common.serialization.proto.IrExpression value_argument = 3;</code>
         */
        public Builder addValueArgument(
                int index, IrExpression.Builder builderForValue) {
            ensureValueArgumentIsMutable();
            valueArgument_.add(index, builderForValue.build());

            return this;
        }

        /**
         * <code>repeated .org.jetbrains.kotlin.backend.common.serialization.proto.IrExpression value_argument = 3;</code>
         */
        public Builder addAllValueArgument(
                Iterable<? extends IrExpression> values) {
            ensureValueArgumentIsMutable();
            addAll(
                    values, valueArgument_);

            return this;
        }

        /**
         * <code>repeated .org.jetbrains.kotlin.backend.common.serialization.proto.IrExpression value_argument = 3;</code>
         */
        public Builder clearValueArgument() {
            valueArgument_ = Collections.emptyList();
            bitField0_ &= ~0x00000004;

            return this;
        }

        /**
         * <code>repeated .org.jetbrains.kotlin.backend.common.serialization.proto.IrExpression value_argument = 3;</code>
         */
        public Builder removeValueArgument(int index) {
            ensureValueArgumentIsMutable();
            valueArgument_.remove(index);

            return this;
        }

        // @@protoc_insertion_point(builder_scope:org.jetbrains.kotlin.backend.common.serialization.proto.IrErrorCallExpression)
    }

    // @@protoc_insertion_point(class_scope:org.jetbrains.kotlin.backend.common.serialization.proto.IrErrorCallExpression)
}
