// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compiler/ir/serialization.common/src/KotlinIr.proto

package org.jetbrains.kotlin.backend.common.serialization.proto;

import org.jetbrains.kotlin.protobuf.AbstractParser;
import org.jetbrains.kotlin.protobuf.ByteString;
import org.jetbrains.kotlin.protobuf.CodedInputStream;
import org.jetbrains.kotlin.protobuf.CodedOutputStream;
import org.jetbrains.kotlin.protobuf.ExtensionRegistryLite;
import org.jetbrains.kotlin.protobuf.GeneratedMessageLite;
import org.jetbrains.kotlin.protobuf.InvalidProtocolBufferException;
import org.jetbrains.kotlin.protobuf.Parser;

import java.io.IOException;
import java.io.InputStream;
import java.io.ObjectStreamException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/**
 * Protobuf type {@code org.jetbrains.kotlin.backend.common.serialization.proto.LocalSignature}
 */
public final class LocalSignature extends
        GeneratedMessageLite implements
        // @@protoc_insertion_point(message_implements:org.jetbrains.kotlin.backend.common.serialization.proto.LocalSignature)
        LocalSignatureOrBuilder {
    public static final int LOCAL_FQ_NAME_FIELD_NUMBER = 1;
    public static final int LOCAL_HASH_FIELD_NUMBER = 2;
    public static final int DEBUG_INFO_FIELD_NUMBER = 3;
    private static final LocalSignature defaultInstance;
    private static final long serialVersionUID = 0L;
    public static Parser<LocalSignature> PARSER =
            new AbstractParser<LocalSignature>() {
                @Override
                public LocalSignature parsePartialFrom(
                        CodedInputStream input,
                        ExtensionRegistryLite extensionRegistry)
                        throws InvalidProtocolBufferException {
                    return new LocalSignature(input, extensionRegistry);
                }
            };

    static {
        defaultInstance = new LocalSignature(true);
        defaultInstance.initFields();
    }

    private final ByteString unknownFields;
    private int bitField0_;
    private List<Integer> localFqName_;
    private int localFqNameMemoizedSerializedSize = -1;
    private long localHash_;
    private int debugInfo_;
    private byte memoizedIsInitialized = -1;
    private int memoizedSerializedSize = -1;

    // Use LocalSignature.newBuilder() to construct.
    private LocalSignature(GeneratedMessageLite.Builder builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
    }

    private LocalSignature(boolean noInit) {
        this.unknownFields = ByteString.EMPTY;
    }
    private LocalSignature(
            CodedInputStream input,
            ExtensionRegistryLite extensionRegistry)
            throws InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        ByteString.Output unknownFieldsOutput =
                ByteString.newOutput();
        CodedOutputStream unknownFieldsCodedOutput =
                CodedOutputStream.newInstance(
                        unknownFieldsOutput, 1);
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    default: {
                        if (!parseUnknownField(input, unknownFieldsCodedOutput,
                                extensionRegistry, tag)) {
                            done = true;
                        }
                        break;
                    }
                    case 8: {
                        if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                            localFqName_ = new ArrayList<Integer>();
                            mutable_bitField0_ |= 0x00000001;
                        }
                        localFqName_.add(input.readInt32());
                        break;
                    }
                    case 10: {
                        int length = input.readRawVarint32();
                        int limit = input.pushLimit(length);
                        if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
                            localFqName_ = new ArrayList<Integer>();
                            mutable_bitField0_ |= 0x00000001;
                        }
                        while (input.getBytesUntilLimit() > 0) {
                            localFqName_.add(input.readInt32());
                        }
                        input.popLimit(limit);
                        break;
                    }
                    case 16: {
                        bitField0_ |= 0x00000001;
                        localHash_ = input.readInt64();
                        break;
                    }
                    case 24: {
                        bitField0_ |= 0x00000002;
                        debugInfo_ = input.readInt32();
                        break;
                    }
                }
            }
        } catch (InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (IOException e) {
            throw new InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this);
        } finally {
            if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                localFqName_ = Collections.unmodifiableList(localFqName_);
            }
            try {
                unknownFieldsCodedOutput.flush();
            } catch (IOException e) {
                // Should not happen
            } finally {
                unknownFields = unknownFieldsOutput.toByteString();
            }
            makeExtensionsImmutable();
        }
    }

    public static LocalSignature getDefaultInstance() {
        return defaultInstance;
    }

    public static LocalSignature parseFrom(
            ByteString data)
            throws InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static LocalSignature parseFrom(
            ByteString data,
            ExtensionRegistryLite extensionRegistry)
            throws InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static LocalSignature parseFrom(byte[] data)
            throws InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static LocalSignature parseFrom(
            byte[] data,
            ExtensionRegistryLite extensionRegistry)
            throws InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static LocalSignature parseFrom(InputStream input)
            throws IOException {
        return PARSER.parseFrom(input);
    }

    public static LocalSignature parseFrom(
            InputStream input,
            ExtensionRegistryLite extensionRegistry)
            throws IOException {
        return PARSER.parseFrom(input, extensionRegistry);
    }

    public static LocalSignature parseDelimitedFrom(InputStream input)
            throws IOException {
        return PARSER.parseDelimitedFrom(input);
    }

    public static LocalSignature parseDelimitedFrom(
            InputStream input,
            ExtensionRegistryLite extensionRegistry)
            throws IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }

    public static LocalSignature parseFrom(
            CodedInputStream input)
            throws IOException {
        return PARSER.parseFrom(input);
    }

    public static LocalSignature parseFrom(
            CodedInputStream input,
            ExtensionRegistryLite extensionRegistry)
            throws IOException {
        return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() {
        return Builder.create();
    }

    public static Builder newBuilder(LocalSignature prototype) {
        return newBuilder().mergeFrom(prototype);
    }

    @Override
    public LocalSignature getDefaultInstanceForType() {
        return defaultInstance;
    }

    @Override
    public Parser<LocalSignature> getParserForType() {
        return PARSER;
    }

    /**
     * <code>repeated int32 local_fq_name = 1 [packed = true];</code>
     */
    @Override
    public List<Integer>
    getLocalFqNameList() {
        return localFqName_;
    }

    /**
     * <code>repeated int32 local_fq_name = 1 [packed = true];</code>
     */
    @Override
    public int getLocalFqNameCount() {
        return localFqName_.size();
    }

    /**
     * <code>repeated int32 local_fq_name = 1 [packed = true];</code>
     */
    @Override
    public int getLocalFqName(int index) {
        return localFqName_.get(index);
    }

    /**
     * <code>optional int64 local_hash = 2;</code>
     */
    @Override
    public boolean hasLocalHash() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
    }

    /**
     * <code>optional int64 local_hash = 2;</code>
     */
    @Override
    public long getLocalHash() {
        return localHash_;
    }

    /**
     * <code>optional int32 debug_info = 3;</code>
     */
    @Override
    public boolean hasDebugInfo() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
    }

    /**
     * <code>optional int32 debug_info = 3;</code>
     */
    @Override
    public int getDebugInfo() {
        return debugInfo_;
    }

    private void initFields() {
        localFqName_ = Collections.emptyList();
        localHash_ = 0L;
        debugInfo_ = 0;
    }

    @Override
    public boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    @Override
    public void writeTo(CodedOutputStream output)
            throws IOException {
        getSerializedSize();
        if (getLocalFqNameList().size() > 0) {
            output.writeRawVarint32(10);
            output.writeRawVarint32(localFqNameMemoizedSerializedSize);
        }
        for (int i = 0; i < localFqName_.size(); i++) {
            output.writeInt32NoTag(localFqName_.get(i));
        }
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
            output.writeInt64(2, localHash_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
            output.writeInt32(3, debugInfo_);
        }
        output.writeRawBytes(unknownFields);
    }

    @Override
    public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        {
            int dataSize = 0;
            for (int i = 0; i < localFqName_.size(); i++) {
                dataSize += CodedOutputStream
                        .computeInt32SizeNoTag(localFqName_.get(i));
            }
            size += dataSize;
            if (!getLocalFqNameList().isEmpty()) {
                size += 1;
                size += CodedOutputStream
                        .computeInt32SizeNoTag(dataSize);
            }
            localFqNameMemoizedSerializedSize = dataSize;
        }
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
            size += CodedOutputStream
                    .computeInt64Size(2, localHash_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
            size += CodedOutputStream
                    .computeInt32Size(3, debugInfo_);
        }
        size += unknownFields.size();
        memoizedSerializedSize = size;
        return size;
    }

    @Override
    protected Object writeReplace()
            throws ObjectStreamException {
        return super.writeReplace();
    }

    @Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    @Override
    public Builder toBuilder() {
        return newBuilder(this);
    }

    /**
     * Protobuf type {@code org.jetbrains.kotlin.backend.common.serialization.proto.LocalSignature}
     */
    public static final class Builder extends
            GeneratedMessageLite.Builder<
                    LocalSignature, Builder>
            implements
            // @@protoc_insertion_point(builder_implements:org.jetbrains.kotlin.backend.common.serialization.proto.LocalSignature)
            LocalSignatureOrBuilder {
        private int bitField0_;
        private List<Integer> localFqName_ = Collections.emptyList();
        private long localHash_;
        private int debugInfo_;

        // Construct using org.jetbrains.kotlin.backend.common.serialization.proto.LocalSignature.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private static Builder create() {
            return new Builder();
        }

        private void maybeForceBuilderInitialization() {
        }

        @Override
        public Builder clear() {
            super.clear();
            localFqName_ = Collections.emptyList();
            bitField0_ &= ~0x00000001;
            localHash_ = 0L;
            bitField0_ &= ~0x00000002;
            debugInfo_ = 0;
            bitField0_ &= ~0x00000004;
            return this;
        }

        @Override
        public Builder clone() {
            return create().mergeFrom(buildPartial());
        }

        @Override
        public LocalSignature getDefaultInstanceForType() {
            return getDefaultInstance();
        }

        @Override
        public LocalSignature build() {
            LocalSignature result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @Override
        public LocalSignature buildPartial() {
            LocalSignature result = new LocalSignature(this);
            int from_bitField0_ = bitField0_;
            int to_bitField0_ = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                localFqName_ = Collections.unmodifiableList(localFqName_);
                bitField0_ &= ~0x00000001;
            }
            result.localFqName_ = localFqName_;
            if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                to_bitField0_ |= 0x00000001;
            }
            result.localHash_ = localHash_;
            if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
                to_bitField0_ |= 0x00000002;
            }
            result.debugInfo_ = debugInfo_;
            result.bitField0_ = to_bitField0_;
            return result;
        }

        @Override
        public Builder mergeFrom(LocalSignature other) {
            if (other == getDefaultInstance())
                return this;
            if (!other.localFqName_.isEmpty()) {
                if (localFqName_.isEmpty()) {
                    localFqName_ = other.localFqName_;
                    bitField0_ &= ~0x00000001;
                } else {
                    ensureLocalFqNameIsMutable();
                    localFqName_.addAll(other.localFqName_);
                }

            }
            if (other.hasLocalHash()) {
                setLocalHash(other.getLocalHash());
            }
            if (other.hasDebugInfo()) {
                setDebugInfo(other.getDebugInfo());
            }
            setUnknownFields(
                    getUnknownFields().concat(other.unknownFields));
            return this;
        }

        @Override
        public boolean isInitialized() {
            return true;
        }

        @Override
        public Builder mergeFrom(
                CodedInputStream input,
                ExtensionRegistryLite extensionRegistry)
                throws IOException {
            LocalSignature parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (InvalidProtocolBufferException e) {
                parsedMessage = (LocalSignature) e.getUnfinishedMessage();
                throw e;
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        private void ensureLocalFqNameIsMutable() {
            if (!((bitField0_ & 0x00000001) == 0x00000001)) {
                localFqName_ = new ArrayList<Integer>(localFqName_);
                bitField0_ |= 0x00000001;
            }
        }

        /**
         * <code>repeated int32 local_fq_name = 1 [packed = true];</code>
         */
        @Override
        public List<Integer>
        getLocalFqNameList() {
            return Collections.unmodifiableList(localFqName_);
        }

        /**
         * <code>repeated int32 local_fq_name = 1 [packed = true];</code>
         */
        @Override
        public int getLocalFqNameCount() {
            return localFqName_.size();
        }

        /**
         * <code>repeated int32 local_fq_name = 1 [packed = true];</code>
         */
        @Override
        public int getLocalFqName(int index) {
            return localFqName_.get(index);
        }

        /**
         * <code>repeated int32 local_fq_name = 1 [packed = true];</code>
         */
        public Builder setLocalFqName(
                int index, int value) {
            ensureLocalFqNameIsMutable();
            localFqName_.set(index, value);

            return this;
        }

        /**
         * <code>repeated int32 local_fq_name = 1 [packed = true];</code>
         */
        public Builder addLocalFqName(int value) {
            ensureLocalFqNameIsMutable();
            localFqName_.add(value);

            return this;
        }

        /**
         * <code>repeated int32 local_fq_name = 1 [packed = true];</code>
         */
        public Builder addAllLocalFqName(
                Iterable<? extends Integer> values) {
            ensureLocalFqNameIsMutable();
            addAll(
                    values, localFqName_);

            return this;
        }

        /**
         * <code>repeated int32 local_fq_name = 1 [packed = true];</code>
         */
        public Builder clearLocalFqName() {
            localFqName_ = Collections.emptyList();
            bitField0_ &= ~0x00000001;

            return this;
        }

        /**
         * <code>optional int64 local_hash = 2;</code>
         */
        @Override
        public boolean hasLocalHash() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        /**
         * <code>optional int64 local_hash = 2;</code>
         */
        @Override
        public long getLocalHash() {
            return localHash_;
        }

        /**
         * <code>optional int64 local_hash = 2;</code>
         */
        public Builder setLocalHash(long value) {
            bitField0_ |= 0x00000002;
            localHash_ = value;

            return this;
        }

        /**
         * <code>optional int64 local_hash = 2;</code>
         */
        public Builder clearLocalHash() {
            bitField0_ &= ~0x00000002;
            localHash_ = 0L;

            return this;
        }

        /**
         * <code>optional int32 debug_info = 3;</code>
         */
        @Override
        public boolean hasDebugInfo() {
            return ((bitField0_ & 0x00000004) == 0x00000004);
        }

        /**
         * <code>optional int32 debug_info = 3;</code>
         */
        @Override
        public int getDebugInfo() {
            return debugInfo_;
        }

        /**
         * <code>optional int32 debug_info = 3;</code>
         */
        public Builder setDebugInfo(int value) {
            bitField0_ |= 0x00000004;
            debugInfo_ = value;

            return this;
        }

        /**
         * <code>optional int32 debug_info = 3;</code>
         */
        public Builder clearDebugInfo() {
            bitField0_ &= ~0x00000004;
            debugInfo_ = 0;

            return this;
        }

        // @@protoc_insertion_point(builder_scope:org.jetbrains.kotlin.backend.common.serialization.proto.LocalSignature)
    }

    // @@protoc_insertion_point(class_scope:org.jetbrains.kotlin.backend.common.serialization.proto.LocalSignature)
}
